import { describe,expect,it,vi } from "vitest";
import { FakeAgentRuntime, type AgentResult, type AgentTask, type RuntimeStatus, type RuntimeStore } from "@software-builder/agent-runtime";
import { AgentJobLeaseLostError, type AgentJobClaim, type AgentJobRepository } from "@software-builder/database";
import { AgentJobProcessor, JobExecutionControl } from "./job-processor.js";
import { BackgroundWorker } from "./worker-loop.js";

const task=(scenario:AgentTask["scenario"]):AgentTask=>({schemaVersion:1,projectId:"project/1",taskId:"task/1",attemptId:"attempt/1",runId:`run/${scenario.toLowerCase()}`,role:"EXECUTOR",scenario,inputRef:"synthetic/input",repairOrdinal:0});
const claim=(scenario:AgentTask["scenario"],extra:Partial<AgentJobClaim>={}):AgentJobClaim=>({jobId:"job/1",projectId:"project/1",task:task(scenario),workerId:"worker/1",claimId:"claim/1",fencingToken:1,leaseGeneration:1,jobVersion:1,leaseExpiresAt:new Date(Date.now()+10_000),retryCount:0,maxRetries:2,cancelRequested:false,cancellationRequestId:null,cancellationSequence:null,completionSequence:null,runtimeWatermark:0,cancelAttemptCount:0,cancelMaxAttempts:3,cancelRemainingAttempts:3,cancelLastOutcome:null,cancelLastErrorCode:null,cancelConfirmedAt:null,cancelConfirmationKind:null,...extra});
const repository=()=>({
  authorizeRuntimeStart:vi.fn(async()=>undefined),
  appendProgress:vi.fn(async(guard:unknown,progress:unknown)=>{void guard;void progress;}),
  scheduleRetry:vi.fn(async(guard:unknown,code:unknown,delay:unknown)=>{void guard;void code;void delay;return{};}),
  complete:vi.fn(async(guard:unknown,result:unknown,message:unknown)=>{void guard;void result;void message;return{};}),
  confirmCancelled:vi.fn(async(guard:unknown,result:unknown,message:unknown)=>{void guard;void result;void message;return{};}),
  verifyTerminationEvidence:vi.fn(async()=>({validity:"VALID" as const,rejectionReason:null,evidenceId:"evidence/1"})),
  markCancellationStuck:vi.fn(async()=>({})),
  beginCancellationAttempt:vi.fn(async()=>({started:true as const,attempt:1,maxAttempts:3})),
  recordCancellationFailure:vi.fn(async()=>({})),
  recordCancellationReconciliation:vi.fn(async()=>undefined),
  fail:vi.fn(async(guard:unknown,code:unknown)=>{void guard;void code;return{};}),claimNext:vi.fn(),heartbeat:vi.fn(),loadClaim:vi.fn(async()=>claim("SUCCESS",{cancelRequested:true,cancellationRequestId:"00000000-0000-4000-8000-000000000001",cancellationSequence:2})),loadRuntimeSnapshot:vi.fn(async():Promise<unknown>=>undefined),saveRuntimeSnapshot:vi.fn(async()=>undefined),
});
const runtimeFactory=(store:RuntimeStore)=>new FakeAgentRuntime({store,now:()=>new Date("2026-01-01T00:00:00.000Z")});
const cancelledResult=(item:AgentJobClaim):AgentResult=>({schemaVersion:1,projectId:item.projectId,taskId:item.task.taskId,attemptId:item.task.attemptId,runId:item.task.runId,status:"CANCELLED",findings:[],artifacts:[],decisions:[],errorCode:null});
const cancelledStatus=(item:AgentJobClaim):RuntimeStatus=>({runId:item.task.runId,state:"CANCELLED",retryCount:0,terminal:true,result:cancelledResult(item),progress:[{schemaVersion:1,runId:item.task.runId,sequence:1,phase:"CANCELLING",occurredAt:new Date().toISOString()},{schemaVersion:1,runId:item.task.runId,sequence:2,phase:"FINISHED",occurredAt:new Date().toISOString()}]});
const deferred=<T=void>()=>{let resolve!:(value:T|PromiseLike<T>)=>void;const promise=new Promise<T>(done=>{resolve=done;});return{promise,resolve};};
const persistedSnapshot=(item:AgentJobClaim)=>({schemaVersion:1,binding:{runId:item.task.runId,projectId:item.projectId,taskId:item.task.taskId,attemptId:item.task.attemptId,fencingToken:item.fencingToken},startKey:"persisted-start",task:item.task,state:"RUNNING",retryCount:0,result:null,progress:[],commands:[]});

describe("AgentJobProcessor",()=>{
  it("persists deterministic success and ordered progress",async()=>{const repo=repository();const processor=new AgentJobProcessor(repo as unknown as AgentJobRepository,{runtimeFactory});await processor.process(claim("SUCCESS"));expect(repo.appendProgress.mock.calls.map(call=>(call[1] as unknown as {sequence:number}).sequence)).toEqual([1,2,3,4]);expect(repo.complete).toHaveBeenCalledOnce();});
  it("turns invalid runtime output into a schema failure",async()=>{const repo=repository();await new AgentJobProcessor(repo as unknown as AgentJobRepository,{runtimeFactory}).process(claim("INVALID_OUTPUT"));expect(repo.fail).toHaveBeenCalledWith(expect.anything(),"AGENT_SCHEMA_INVALID");expect(repo.complete).not.toHaveBeenCalled();});
  it("schedules infrastructure retry and confirms cancellation",async()=>{const retryRepo=repository();await new AgentJobProcessor(retryRepo as unknown as AgentJobRepository,{runtimeFactory}).process(claim("RETRY"));expect(retryRepo.scheduleRetry).toHaveBeenCalledWith(expect.anything(),"FAKE_INFRA_RETRY",0);const cancelRepo=repository();await new AgentJobProcessor(cancelRepo as unknown as AgentJobRepository,{runtimeFactory}).process(claim("SUCCESS",{cancelRequested:true,cancellationRequestId:"00000000-0000-4000-8000-000000000001",cancellationSequence:2}));expect(cancelRepo.beginCancellationAttempt).toHaveBeenCalledOnce();expect(cancelRepo.verifyTerminationEvidence).toHaveBeenCalledOnce();expect(cancelRepo.confirmCancelled).toHaveBeenCalledWith(expect.anything(),expect.objectContaining({status:"CANCELLED"}),expect.any(String),expect.any(String));expect(cancelRepo.complete).not.toHaveBeenCalled();});
  it.each([
    ["FAILED",async()=>{throw new Error("provider failure");},"RUNTIME_CANCEL_FAILED"],
    ["REJECTED",async(item:AgentJobClaim)=>({runId:item.task.runId,state:"RUNNING" as const,retryCount:0,terminal:false,result:null,progress:[]}),"RUNTIME_CANCEL_REJECTED"],
  ] as const)("persists %s runtime cancellation without synthetic confirmation",async(outcome,cancel,errorCode)=>{const repo=repository();const item=claim("SUCCESS",{cancelRequested:true});const runtime={startRun:async()=>{throw new Error("unexpected");},continueRun:async()=>{throw new Error("unexpected");},cancelRun:()=>cancel(item),getRunStatus:async()=>{throw new Error("unexpected");}};await new AgentJobProcessor(repo as unknown as AgentJobRepository,{runtimeFactory:()=>runtime}).process(item);expect(repo.recordCancellationFailure).toHaveBeenCalledWith(expect.anything(),outcome,errorCode,0,0);expect(repo.confirmCancelled).not.toHaveBeenCalled();expect(repo.complete).not.toHaveBeenCalled();});
  it("persists runtime cancellation timeout without synthetic confirmation",async()=>{const repo=repository();const item=claim("SUCCESS",{cancelRequested:true});const runtime={startRun:async()=>{throw new Error("unexpected");},continueRun:async()=>{throw new Error("unexpected");},cancelRun:async()=>new Promise<RuntimeStatus>(()=>undefined),getRunStatus:async()=>{throw new Error("unexpected");}};await new AgentJobProcessor(repo as unknown as AgentJobRepository,{runtimeFactory:()=>runtime,cancellationTimeoutMs:5}).process(item);expect(repo.recordCancellationFailure).toHaveBeenCalledWith(expect.anything(),"TIMED_OUT","RUNTIME_CANCEL_TIMEOUT",0,0);expect(repo.confirmCancelled).not.toHaveBeenCalled();});
  it("AT-15/AT-17 fails closed when the mandatory recovery status query fails",async()=>{const repo=repository();const item=claim("SUCCESS",{cancelRequested:true,cancellationRequestId:"00000000-0000-4000-8000-000000000001",cancellationSequence:2,cancelAttemptCount:1,cancelRemainingAttempts:2});repo.loadRuntimeSnapshot.mockResolvedValue(persistedSnapshot(item));const runtime={startRun:async()=>{throw new Error("unexpected");},continueRun:async()=>{throw new Error("unexpected");},cancelRun:async()=>{throw new Error("unexpected");},getRunStatus:async()=>{throw new Error("STATUS_QUERY_FAILED");}};await expect(new AgentJobProcessor(repo as unknown as AgentJobRepository,{runtimeFactory:()=>runtime}).process(item)).rejects.toThrow("STATUS_QUERY_FAILED");expect(repo.recordCancellationReconciliation).not.toHaveBeenCalled();expect(repo.beginCancellationAttempt).not.toHaveBeenCalled();expect(repo.markCancellationStuck).not.toHaveBeenCalled();});
  it("AT-18 discards a late runtime success before recovery reconciliation and never publishes it",async()=>{const repo=repository();const item=claim("SUCCESS",{cancelRequested:true,cancellationRequestId:"00000000-0000-4000-8000-000000000001",cancellationSequence:2,cancelAttemptCount:1,cancelRemainingAttempts:2});repo.loadRuntimeSnapshot.mockResolvedValue(persistedSnapshot(item));const result:AgentResult={schemaVersion:1,projectId:item.projectId,taskId:item.task.taskId,attemptId:item.task.attemptId,runId:item.task.runId,status:"SUCCESS",findings:[],artifacts:[],decisions:[],errorCode:null};const status:RuntimeStatus={runId:item.task.runId,state:"SUCCEEDED",retryCount:0,terminal:true,result,progress:[]};const runtime={startRun:async()=>{throw new Error("unexpected");},continueRun:async()=>{throw new Error("unexpected");},cancelRun:async()=>({runId:item.task.runId,state:"RUNNING" as const,retryCount:0,terminal:false,result:null,progress:[]}),getRunStatus:async()=>status};await new AgentJobProcessor(repo as unknown as AgentJobRepository,{runtimeFactory:()=>runtime}).process(item);expect(repo.complete).toHaveBeenCalledWith(expect.anything(),result,expect.any(String));expect(repo.recordCancellationReconciliation).toHaveBeenCalledOnce();expect(repo.beginCancellationAttempt).toHaveBeenCalledOnce();expect(repo.confirmCancelled).not.toHaveBeenCalled();});
  it("gives cancellation priority after result computation and before completion",async()=>{const repo=repository();const item=claim("SUCCESS");const control=new JobExecutionControl();await new AgentJobProcessor(repo as unknown as AgentJobRepository,{runtimeFactory,beforeCompletionCommit:()=>control.requestCancellation()}).process(item,control);expect(repo.confirmCancelled).toHaveBeenCalledOnce();expect(repo.complete).not.toHaveBeenCalled();});
});

describe("BackgroundWorker",()=>{
  it("periodically heartbeats while processing",async()=>{const repo=repository();const item=claim("SUCCESS");const finished=deferred();repo.claimNext.mockResolvedValueOnce(item).mockResolvedValueOnce(null);repo.loadClaim.mockResolvedValue(item);repo.heartbeat.mockImplementation(async()=>{if(repo.heartbeat.mock.calls.length===2)finished.resolve();return item;});const process=vi.fn(async()=>finished.promise);const worker=new BackgroundWorker(repo as unknown as AgentJobRepository,{process} as never,{workerId:"worker/1",leaseMs:100,heartbeatIntervalMs:10,wait:async()=>undefined});expect(await worker.drain()).toBe(1);expect(repo.heartbeat).toHaveBeenCalledTimes(2);expect(process).toHaveBeenCalledOnce();worker.stop();expect(await worker.runOnce()).toBe(false);});
  it("observes in-flight cancellation at a controlled heartbeat boundary without trusting a status string",async()=>{const repo=repository();const item=claim("SUCCESS");const runtimeRelease=deferred();repo.claimNext.mockResolvedValue(item);repo.loadClaim.mockResolvedValue({...item,cancelRequested:true,cancellationRequestId:"00000000-0000-4000-8000-000000000001",cancellationSequence:2});repo.heartbeat.mockImplementation(async()=>{runtimeRelease.resolve();return{...item,cancelRequested:true};});const cancelRun=vi.fn(async()=>cancelledStatus(item));const processor=new AgentJobProcessor(repo as unknown as AgentJobRepository,{runtimeFactory:()=>({startRun:async()=>{await runtimeRelease.promise;return{runId:item.task.runId,state:"RUNNING",retryCount:0,terminal:false,result:null,progress:[]};},continueRun:async()=>{throw new Error("unexpected");},cancelRun,getRunStatus:async()=>{throw new Error("unexpected");}})});const worker=new BackgroundWorker(repo as unknown as AgentJobRepository,processor,{workerId:"worker/1",leaseMs:100,heartbeatIntervalMs:10,wait:async()=>undefined});await worker.runOnce();expect(cancelRun).toHaveBeenCalled();expect(repo.recordCancellationFailure).toHaveBeenCalledWith(expect.anything(),"REJECTED","TERMINATION_EVIDENCE_MISSING",0,2);expect(repo.confirmCancelled).not.toHaveBeenCalled();expect(repo.complete).not.toHaveBeenCalled();});
  it("performs no runtime or persistent mutation after controlled lease loss",async()=>{const repo=repository();const item=claim("SUCCESS");const runtimeRelease=deferred();repo.claimNext.mockResolvedValue(item);repo.loadClaim.mockImplementation(async()=>{runtimeRelease.resolve();throw new AgentJobLeaseLostError();});const cancelRun=vi.fn(async()=>cancelledStatus(item));const processor=new AgentJobProcessor(repo as unknown as AgentJobRepository,{runtimeFactory:()=>({startRun:async()=>{await runtimeRelease.promise;return{runId:item.task.runId,state:"RUNNING",retryCount:0,terminal:false,result:null,progress:[]};},continueRun:async()=>{throw new Error("unexpected");},cancelRun,getRunStatus:async()=>{throw new Error("unexpected");}})});const worker=new BackgroundWorker(repo as unknown as AgentJobRepository,processor,{workerId:"worker/1",leaseMs:100,heartbeatIntervalMs:10,wait:async()=>undefined});await worker.runOnce();expect(cancelRun).not.toHaveBeenCalled();expect(repo.complete).not.toHaveBeenCalled();expect(repo.confirmCancelled).not.toHaveBeenCalled();expect(repo.appendProgress).not.toHaveBeenCalled();});
});
