import { describe,expect,it,vi } from "vitest";
import { FakeAgentRuntime, type AgentResult, type AgentTask, type RuntimeStatus, type RuntimeStore } from "@software-builder/agent-runtime";
import { AgentJobLeaseLostError, type AgentJobClaim, type AgentJobRepository } from "@software-builder/database";
import { AgentJobProcessor } from "./job-processor.js";
import { BackgroundWorker } from "./worker-loop.js";

const task=(scenario:AgentTask["scenario"]):AgentTask=>({schemaVersion:1,projectId:"project/1",taskId:"task/1",attemptId:"attempt/1",runId:`run/${scenario.toLowerCase()}`,role:"EXECUTOR",scenario,inputRef:"synthetic/input",repairOrdinal:0});
const claim=(scenario:AgentTask["scenario"],extra:Partial<AgentJobClaim>={}):AgentJobClaim=>({jobId:"job/1",projectId:"project/1",task:task(scenario),workerId:"worker/1",claimId:"claim/1",fencingToken:1,leaseExpiresAt:new Date(Date.now()+10_000),retryCount:0,maxRetries:2,cancelRequested:false,...extra});
const repository=()=>({
  appendProgress:vi.fn(async(guard:unknown,progress:unknown)=>{void guard;void progress;}),
  scheduleRetry:vi.fn(async(guard:unknown,code:unknown,delay:unknown)=>{void guard;void code;void delay;return{};}),
  complete:vi.fn(async(guard:unknown,result:unknown,message:unknown)=>{void guard;void result;void message;return{};}),
  confirmCancelled:vi.fn(async(guard:unknown,result:unknown,message:unknown)=>{void guard;void result;void message;return{};}),
  fail:vi.fn(async(guard:unknown,code:unknown)=>{void guard;void code;return{};}),claimNext:vi.fn(),heartbeat:vi.fn(),loadClaim:vi.fn(),loadRuntimeSnapshot:vi.fn(async()=>undefined),saveRuntimeSnapshot:vi.fn(async()=>undefined),
});
const runtimeFactory=(store:RuntimeStore)=>new FakeAgentRuntime({store,now:()=>new Date("2026-01-01T00:00:00.000Z")});
const cancelledResult=(item:AgentJobClaim):AgentResult=>({schemaVersion:1,projectId:item.projectId,taskId:item.task.taskId,attemptId:item.task.attemptId,runId:item.task.runId,status:"CANCELLED",findings:[],artifacts:[],decisions:[],errorCode:null});
const cancelledStatus=(item:AgentJobClaim):RuntimeStatus=>({runId:item.task.runId,state:"CANCELLED",retryCount:0,terminal:true,result:cancelledResult(item),progress:[{schemaVersion:1,runId:item.task.runId,sequence:1,phase:"CANCELLING",occurredAt:new Date().toISOString()},{schemaVersion:1,runId:item.task.runId,sequence:2,phase:"FINISHED",occurredAt:new Date().toISOString()}]});

describe("AgentJobProcessor",()=>{
  it("persists deterministic success and ordered progress",async()=>{const repo=repository();const processor=new AgentJobProcessor(repo as unknown as AgentJobRepository,{runtimeFactory});await processor.process(claim("SUCCESS"));expect(repo.appendProgress.mock.calls.map(call=>(call[1] as unknown as {sequence:number}).sequence)).toEqual([1,2,3,4]);expect(repo.complete).toHaveBeenCalledOnce();});
  it("turns invalid runtime output into a schema failure",async()=>{const repo=repository();await new AgentJobProcessor(repo as unknown as AgentJobRepository,{runtimeFactory}).process(claim("INVALID_OUTPUT"));expect(repo.fail).toHaveBeenCalledWith(expect.anything(),"AGENT_SCHEMA_INVALID");expect(repo.complete).not.toHaveBeenCalled();});
  it("schedules infrastructure retry and confirms cancellation",async()=>{const retryRepo=repository();await new AgentJobProcessor(retryRepo as unknown as AgentJobRepository,{runtimeFactory}).process(claim("RETRY"));expect(retryRepo.scheduleRetry).toHaveBeenCalledWith(expect.anything(),"FAKE_INFRA_RETRY",0);const cancelRepo=repository();await new AgentJobProcessor(cancelRepo as unknown as AgentJobRepository,{runtimeFactory}).process(claim("SUCCESS",{cancelRequested:true}));expect(cancelRepo.confirmCancelled).toHaveBeenCalledOnce();expect(cancelRepo.complete).not.toHaveBeenCalled();});
});

describe("BackgroundWorker",()=>{
  it("periodically heartbeats while processing",async()=>{const repo=repository();const item=claim("SUCCESS");repo.claimNext.mockResolvedValueOnce(item).mockResolvedValueOnce(null);repo.loadClaim.mockResolvedValue(item);repo.heartbeat.mockResolvedValue(item);const process=vi.fn(async()=>new Promise<void>(resolve=>setTimeout(resolve,35)));const worker=new BackgroundWorker(repo as unknown as AgentJobRepository,{process} as never,{workerId:"worker/1",leaseMs:100,heartbeatIntervalMs:10});expect(await worker.drain()).toBe(1);expect(repo.heartbeat.mock.calls.length).toBeGreaterThanOrEqual(2);expect(process).toHaveBeenCalledOnce();worker.stop();expect(await worker.runOnce()).toBe(false);});
  it("observes in-flight cancellation during a slow runtime",async()=>{const repo=repository();const item=claim("SUCCESS");repo.claimNext.mockResolvedValue(item);repo.loadClaim.mockResolvedValue({...item,cancelRequested:true});repo.heartbeat.mockResolvedValue({...item,cancelRequested:true});const cancelRun=vi.fn(async()=>cancelledStatus(item));const processor=new AgentJobProcessor(repo as unknown as AgentJobRepository,{runtimeFactory:()=>({startRun:async()=>{await new Promise(resolve=>setTimeout(resolve,35));return{runId:item.task.runId,state:"RUNNING",retryCount:0,terminal:false,result:null,progress:[]};},continueRun:async()=>{throw new Error("unexpected");},cancelRun,getRunStatus:async()=>{throw new Error("unexpected");}})});const worker=new BackgroundWorker(repo as unknown as AgentJobRepository,processor,{workerId:"worker/1",leaseMs:100,heartbeatIntervalMs:10});await worker.runOnce();expect(cancelRun).toHaveBeenCalled();expect(repo.confirmCancelled).toHaveBeenCalledOnce();expect(repo.complete).not.toHaveBeenCalled();});
  it("best-effort cancels and performs no stale mutation after lease loss",async()=>{const repo=repository();const item=claim("SUCCESS");repo.claimNext.mockResolvedValue(item);repo.loadClaim.mockRejectedValue(new AgentJobLeaseLostError());const cancelRun=vi.fn(async()=>cancelledStatus(item));const processor=new AgentJobProcessor(repo as unknown as AgentJobRepository,{runtimeFactory:()=>({startRun:async()=>{await new Promise(resolve=>setTimeout(resolve,35));return{runId:item.task.runId,state:"RUNNING",retryCount:0,terminal:false,result:null,progress:[]};},continueRun:async()=>{throw new Error("unexpected");},cancelRun,getRunStatus:async()=>{throw new Error("unexpected");}})});const worker=new BackgroundWorker(repo as unknown as AgentJobRepository,processor,{workerId:"worker/1",leaseMs:100,heartbeatIntervalMs:10});await worker.runOnce();expect(cancelRun).toHaveBeenCalled();expect(repo.complete).not.toHaveBeenCalled();expect(repo.confirmCancelled).not.toHaveBeenCalled();expect(repo.appendProgress).not.toHaveBeenCalled();});
});
