import { canonicalAgentOperationDigest, parseAgentResult, parseAgentTask, parseProgress, type AgentRuntimeOperation, type RuntimeCommand, type RuntimeStatus, type RuntimeStore, type RuntimeStoredRun } from "@software-builder/agent-runtime";
import type { AgentJobClaim, AgentJobGuard, AgentJobRepository } from "@software-builder/database";

interface StoredSnapshot { readonly schemaVersion:1;readonly binding:RuntimeStoredRun["binding"];readonly startKey:string;readonly task:RuntimeStoredRun["task"];readonly state:RuntimeStoredRun["state"];readonly retryCount:number;readonly result:RuntimeStoredRun["result"];readonly progress:RuntimeStoredRun["progress"];readonly commands:readonly [string,{digest:string;fence:number;status:RuntimeStatus}][]; }

/** Claim-scoped durable runtime state. Every read/write is protected by the active exact fence. */
export class PostgresRuntimeStore implements RuntimeStore {
  constructor(private readonly repository:AgentJobRepository,readonly claim:AgentJobClaim) {}
  command(operation:AgentRuntimeOperation):RuntimeCommand {const task=this.claim.task;const terminationContext=this.claim.cancellationRequestId&&this.claim.cancellationSequence!==null?{projectId:this.claim.projectId,runtimeId:task.runId,agentRunId:task.runId,attemptId:task.attemptId,jobId:this.claim.jobId,cancellationRequestId:this.claim.cancellationRequestId,workloadId:`fake-workload:${task.runId}`,processIdentity:null,allowedLeaseGenerations:[this.claim.leaseGeneration],allowedFencingTokens:[this.claim.fencingToken],cancellationSequence:this.claim.cancellationSequence,minimumRuntimeEventSequence:this.claim.runtimeWatermark,environment:"DEVELOPMENT" as const,policyVersion:"cancellation-contract-1",verifierIdentity:"runtime-termination-verifier/v1",now:new Date().toISOString(),maximumAgeMs:86_400_000,trustedIssuers:["fake-agent-runtime/v1"],supportedMethods:["FAKE_DETERMINISTIC_V1" as const]}:undefined;return{runId:task.runId,projectId:task.projectId,taskId:task.taskId,attemptId:task.attemptId,idempotencyKey:`${this.claim.jobId}:${this.claim.fencingToken}:${operation}`,requestDigest:canonicalAgentOperationDigest(operation,task),fencingToken:this.claim.fencingToken,task,terminationContext};}
  guard():AgentJobGuard{return{jobId:this.claim.jobId,workerId:this.claim.workerId,workerProcessIdentity:this.claim.workerProcessIdentity,processLaunchId:this.claim.processLaunchId,claimId:this.claim.claimId,fencingToken:this.claim.fencingToken};}
  async load(runId:string):Promise<RuntimeStoredRun|undefined>{if(runId!==this.claim.task.runId)throw new Error("RUNTIME_STORE_BINDING_MISMATCH");const value=await this.repository.loadRuntimeSnapshot(this.guard());if(!value)return undefined;return decode(value);}
  async save(run:RuntimeStoredRun):Promise<void>{if(run.binding.runId!==this.claim.task.runId)throw new Error("RUNTIME_STORE_BINDING_MISMATCH");const snapshot:StoredSnapshot={schemaVersion:1,binding:run.binding,startKey:run.startKey,task:run.task,state:run.state,retryCount:run.retryCount,result:run.result,progress:run.progress,commands:[...run.commands.entries()]};await this.repository.saveRuntimeSnapshot(this.guard(),snapshot,run.state);}
  async persistProgress(status:RuntimeStatus):Promise<void>{for(const event of status.progress)await this.repository.appendProgress(this.guard(),event);}
}

function decode(value:unknown):RuntimeStoredRun{if(!value||typeof value!=="object")throw new Error("RUNTIME_SNAPSHOT_INVALID");const item=value as Partial<StoredSnapshot>;if(item.schemaVersion!==1||!item.binding||!item.startKey||!item.task||!item.state||!Number.isSafeInteger(item.retryCount)||!Array.isArray(item.progress)||!Array.isArray(item.commands))throw new Error("RUNTIME_SNAPSHOT_INVALID");const task=parseAgentTask(item.task);const progress=item.progress.map(parseProgress);const result=item.result===null?null:parseAgentResult(item.result);const commands=new Map<string,{digest:string;fence:number;status:RuntimeStatus}>(item.commands);return{binding:item.binding,startKey:item.startKey,task,state:item.state,retryCount:item.retryCount!,result,progress,commands};}
