import { AgentJobLeaseLostError, type AgentJobRepository } from "@software-builder/database";
import { AgentJobProcessor, JobExecutionControl } from "./job-processor.js";

export interface WorkerLoopOptions { readonly workerId:string;readonly leaseMs?:number;readonly heartbeatLeaseMs?:number;readonly heartbeatIntervalMs?:number;readonly pollIntervalMs?:number;readonly wait?:(milliseconds:number)=>Promise<void>; }
export class BackgroundWorker {
  private readonly leaseMs:number;private readonly heartbeatLeaseMs:number;private readonly heartbeatIntervalMs:number;private readonly pollIntervalMs:number;private readonly wait:(milliseconds:number)=>Promise<void>;private claimOrdinal=0;private stopped=false;
  constructor(private readonly repository:AgentJobRepository,private readonly processor:AgentJobProcessor,private readonly options:WorkerLoopOptions){this.leaseMs=options.leaseMs??30_000;this.heartbeatLeaseMs=options.heartbeatLeaseMs??this.leaseMs;this.heartbeatIntervalMs=options.heartbeatIntervalMs??Math.max(10,Math.floor(this.leaseMs/3));this.pollIntervalMs=options.pollIntervalMs??250;this.wait=options.wait??delay;if(this.heartbeatIntervalMs>=this.leaseMs)throw new Error("heartbeatIntervalMs must be shorter than leaseMs");}
  stop(){this.stopped=true;}
  async runOnce():Promise<boolean>{if(this.stopped)return false;const claim=await this.repository.claimNext(this.options.workerId,`${this.options.workerId}:claim:${++this.claimOrdinal}`,this.leaseMs);if(!claim)return false;const control=new JobExecutionControl();if(claim.cancelRequested)control.requestCancellation();const processing=this.processor.process(claim,control);let settled=false;void processing.then(()=>{settled=true;},()=>{settled=true;});while(!settled){await Promise.race([processing,this.wait(this.heartbeatIntervalMs)]);if(settled)break;try{const current=await this.repository.loadClaim({jobId:claim.jobId,workerId:claim.workerId,claimId:claim.claimId,fencingToken:claim.fencingToken});if(current.cancelRequested)control.requestCancellation();await this.repository.heartbeat({jobId:claim.jobId,workerId:claim.workerId,claimId:claim.claimId,fencingToken:claim.fencingToken},this.heartbeatLeaseMs);}catch(error){if(error instanceof AgentJobLeaseLostError){control.loseLease();break;}throw error;}}await processing;return true;}
  async run():Promise<void>{while(!this.stopped){const processed=await this.runOnce();if(!processed&&!this.stopped)await this.wait(this.pollIntervalMs);}}
  async drain(maxJobs=100):Promise<number>{if(!Number.isSafeInteger(maxJobs)||maxJobs<1)throw new Error("maxJobs must be positive");let count=0;while(count<maxJobs&&await this.runOnce())count++;return count;}
}
const delay=(milliseconds:number)=>new Promise<void>(resolve=>setTimeout(resolve,milliseconds));
