import { createHash } from "node:crypto";
import { AGENT_SCHEMA_VERSION, canonicalAgentOperationDigest, parseAgentResult, parseAgentTask, type AgentResult, type AgentRuntimeOperation, type Decision, type Finding, type Progress } from "./schemas.js";
import { InMemoryRuntimeStore, type AgentRuntime, type RuntimeCommand, type RuntimeState, type RuntimeStatus, type RuntimeStore, type RuntimeStoredRun, type StartRunCommand } from "./runtime.js";
import { runtimeTerminationAttestationPayloadDigest, runtimeTerminationEvidenceDigest, type RuntimeTerminationEvidenceCandidate } from "./termination-evidence.js";

const terminalStates: readonly RuntimeState[]=["SUCCEEDED","FAILED","TIMED_OUT","CANCELLED","BLOCKED"];
const snapshot=(run:RuntimeStoredRun):RuntimeStatus=>({runId:run.binding.runId,state:run.state,retryCount:run.retryCount,terminal:terminalStates.includes(run.state),result:run.result,progress:[...run.progress]});
const sameBinding=(run:RuntimeStoredRun, command:RuntimeCommand)=>run.binding.runId===command.runId&&run.binding.projectId===command.projectId&&run.binding.taskId===command.taskId&&run.binding.attemptId===command.attemptId;

export interface FakeAgentRuntimeOptions { readonly store?:RuntimeStore; readonly now?:()=>Date; readonly retryLimit?:number; }
export class FakeAgentRuntime implements AgentRuntime {
  private readonly store:RuntimeStore; private readonly now:()=>Date; private readonly retryLimit:number;
  constructor(options:FakeAgentRuntimeOptions={}) { this.store=options.store??new InMemoryRuntimeStore();this.now=options.now??(()=>new Date());this.retryLimit=options.retryLimit??2;if(!Number.isSafeInteger(this.retryLimit)||this.retryLimit<0||this.retryLimit>20)throw new Error("retryLimit must be 0..20"); }
  async startRun(command:StartRunCommand):Promise<RuntimeStatus>{
    const task=parseAgentTask(command.task); this.assertCommand(command,"startRun"); if(task.runId!==command.runId||task.projectId!==command.projectId||task.taskId!==command.taskId||task.attemptId!==command.attemptId)throw new Error("RUNTIME_BINDING_MISMATCH");
    const existing=await this.store.load(command.runId);if(existing)return this.reconcile(existing,command);
    const run:RuntimeStoredRun={binding:{runId:command.runId,projectId:command.projectId,taskId:command.taskId,attemptId:command.attemptId,fencingToken:command.fencingToken},startKey:command.idempotencyKey,task,state:"RUNNING",retryCount:0,result:null,progress:[],commands:new Map()};
    this.progress(run,"STARTED");this.progress(run,"ANALYSING");
    if(task.scenario==="RETRY"){run.state="RETRY_PENDING";this.progress(run,"RETRYING");} else if(task.scenario!=="CANCEL") this.finishScenario(run);
    const status=snapshot(run);run.commands.set(command.idempotencyKey,{digest:command.requestDigest,fence:command.fencingToken,status});await this.store.save(run);return status;
  }
  async continueRun(command:RuntimeCommand):Promise<RuntimeStatus>{const run=await this.owned(command,"continueRun");const replay=this.commandReplay(run,command);if(replay)return replay;if(terminalStates.includes(run.state))return this.record(run,command);if(run.task.scenario==="RETRY"&&run.state==="RETRY_PENDING"){run.retryCount++;if(run.retryCount>this.retryLimit){run.state="FAILED";run.result=this.result(run,"ERROR");}else{this.progress(run,"PRODUCING");run.result=this.result(run,"SUCCESS");run.state="SUCCEEDED";this.progress(run,"FINISHED");}}return this.record(run,command);}
  async cancelRun(command:RuntimeCommand):Promise<RuntimeStatus>{let run=await this.store.load(command.runId);this.assertCommand(command,"cancelRun");if(!run){const task=parseAgentTask(command.task);run={binding:{runId:command.runId,projectId:command.projectId,taskId:command.taskId,attemptId:command.attemptId,fencingToken:command.fencingToken},startKey:command.idempotencyKey,task,state:"RUNNING",retryCount:0,result:null,progress:[],commands:new Map()};}else run=await this.owned(command,"cancelRun");const replay=this.commandReplay(run,command);if(replay)return this.withTerminationEvidence(replay,command);if(!terminalStates.includes(run.state)){run.state="CANCELLATION_REQUESTED";this.progress(run,"CANCELLING");run.result=this.result(run,"CANCELLED");run.state="CANCELLED";this.progress(run,"FINISHED");}return this.withTerminationEvidence(await this.record(run,command),command);}
  async getRunStatus(command:RuntimeCommand):Promise<RuntimeStatus>{const run=await this.owned(command,"getRunStatus");const replay=this.commandReplay(run,command);if(replay)return this.withTerminationEvidence(replay,command);return this.withTerminationEvidence(await this.record(run,command),command);}
  private async owned(command:RuntimeCommand,operation:AgentRuntimeOperation){this.assertCommand(command,operation);const run=await this.store.load(command.runId);if(!run)throw new Error("RUNTIME_RUN_NOT_FOUND");if(!sameBinding(run,command)||canonicalAgentOperationDigest("enqueue",run.task)!==canonicalAgentOperationDigest("enqueue",command.task))throw new Error("RUNTIME_BINDING_MISMATCH");if(command.fencingToken<run.binding.fencingToken)throw new Error("RUNTIME_FENCE_REJECTED");if(command.fencingToken>run.binding.fencingToken){run.binding={...run.binding,fencingToken:command.fencingToken};await this.store.save(run);}return run;}
  private async reconcile(run:RuntimeStoredRun,command:RuntimeCommand){if(!sameBinding(run,command)||canonicalAgentOperationDigest("enqueue",run.task)!==canonicalAgentOperationDigest("enqueue",command.task))throw new Error("RUNTIME_BINDING_MISMATCH");if(command.fencingToken<run.binding.fencingToken)throw new Error("RUNTIME_FENCE_REJECTED");const replay=this.commandReplay(run,command);if(replay)return replay;if(command.fencingToken===run.binding.fencingToken)throw new Error("RUNTIME_RUN_ALREADY_EXISTS");run.binding={...run.binding,fencingToken:command.fencingToken};return this.record(run,command);}
  private commandReplay(run:RuntimeStoredRun,command:RuntimeCommand){const prior=run.commands.get(command.idempotencyKey);if(!prior)return undefined;if(prior.digest!==command.requestDigest)throw new Error("RUNTIME_IDEMPOTENCY_DIVERGED");if(prior.fence!==command.fencingToken)throw new Error("RUNTIME_FENCE_REJECTED");return prior.status;}
  private async record(run:RuntimeStoredRun,command:RuntimeCommand){const status=snapshot(run);run.commands.set(command.idempotencyKey,{digest:command.requestDigest,fence:command.fencingToken,status});await this.store.save(run);return status;}
  private assertCommand(command:RuntimeCommand,operation:AgentRuntimeOperation){const task=parseAgentTask(command.task);if(!command.runId||!command.projectId||!command.taskId||!command.attemptId||!command.idempotencyKey||!Number.isSafeInteger(command.fencingToken)||command.fencingToken<1||task.runId!==command.runId||task.projectId!==command.projectId||task.taskId!==command.taskId||task.attemptId!==command.attemptId||command.requestDigest!==canonicalAgentOperationDigest(operation,task))throw new Error("RUNTIME_COMMAND_INVALID");}
  private progress(run:RuntimeStoredRun,phase:Progress["phase"]){if(terminalStates.includes(run.state)&&phase!=="FINISHED")throw new Error("RUNTIME_TERMINAL_PROGRESS_REJECTED");run.progress.push({schemaVersion:AGENT_SCHEMA_VERSION,runId:run.binding.runId,sequence:run.progress.length+1,phase,occurredAt:this.now().toISOString()});}
  private finishScenario(run:RuntimeStoredRun){this.progress(run,"PRODUCING");switch(run.task.scenario){case"SUCCESS":run.result=this.result(run,"SUCCESS");run.state="SUCCEEDED";break;case"ERROR":run.result=this.result(run,"ERROR");run.state="FAILED";break;case"TIMEOUT":run.result=this.result(run,"TIMEOUT");run.state="TIMED_OUT";break;case"INVALID_OUTPUT":parseAgentResult({...this.result(run,"SUCCESS"),unexpected:true});break;case"SECURITY_BLOCK":run.result=this.result(run,"SECURITY_BLOCK");run.state="BLOCKED";break;case"LEGAL_COUNSEL_REQUIRED":run.result=this.result(run,"LEGAL_COUNSEL_REQUIRED");run.state="BLOCKED";break;}this.progress(run,"FINISHED");}
  private result(run:RuntimeStoredRun,status:AgentResult["status"]):AgentResult{const id=(kind:string)=>`${kind}/${run.binding.runId}`;const findings:Finding[]=status==="SECURITY_BLOCK"?[{schemaVersion:1,findingId:id("finding"),category:"SECURITY",severity:"CRITICAL",status:"BLOCK",evidenceRef:id("evidence")}]:status==="LEGAL_COUNSEL_REQUIRED"?[{schemaVersion:1,findingId:id("finding"),category:"LEGAL",severity:"HIGH",status:"COUNSEL_REQUIRED",evidenceRef:id("evidence")}]:[];const decisions:Decision[]=status==="SECURITY_BLOCK"?[{schemaVersion:1,decisionId:id("decision"),kind:"SECURITY",outcome:"BLOCK",rationaleRef:id("rationale")}]:status==="LEGAL_COUNSEL_REQUIRED"?[{schemaVersion:1,decisionId:id("decision"),kind:"LEGAL",outcome:"COUNSEL_REQUIRED",rationaleRef:id("rationale")}]:[];return parseAgentResult({schemaVersion:1,projectId:run.binding.projectId,taskId:run.binding.taskId,attemptId:run.binding.attemptId,runId:run.binding.runId,status,findings,artifacts:status==="SUCCESS"?[{schemaVersion:1,artifactId:id("artifact"),kind:"REVISION",objectRef:id("object"),digest:createHash("sha256").update(run.binding.runId).digest("hex")}]:[],decisions,errorCode:status==="ERROR"?"FAKE_ERROR":status==="TIMEOUT"?"FAKE_TIMEOUT":null});}
  private withTerminationEvidence(status:RuntimeStatus,command:RuntimeCommand):RuntimeStatus{const context=command.terminationContext;if(!status.terminal||!context)return status;const idHash=createHash("sha256").update(`fake-evidence\0${context.jobId}\0${context.cancellationRequestId}\0${context.cancellationSequence}\0${status.state}`).digest("hex");const evidenceId=`${idHash.slice(0,8)}-${idHash.slice(8,12)}-4${idHash.slice(13,16)}-a${idHash.slice(17,20)}-${idHash.slice(20,32)}`;const runtimeEventSequence=Math.max(context.minimumRuntimeEventSequence,status.progress.at(-1)?.sequence??0);const terminalState=status.state as RuntimeTerminationEvidenceCandidate["terminalState"];const attestationPayload={format:"FAKE_DETERMINISTIC_V1" as const,terminalState,workloadId:context.workloadId!,runtimeEventSequence};const claims:Omit<RuntimeTerminationEvidenceCandidate,"evidenceDigest">={schemaVersion:1,evidenceId,evidenceType:"FAKE_RUNTIME_TERMINATION",projectId:context.projectId,runtimeId:context.runtimeId,agentRunId:context.agentRunId,attemptId:context.attemptId,jobId:context.jobId,cancellationRequestId:context.cancellationRequestId,workloadId:context.workloadId,processIdentity:context.processIdentity,leaseGeneration:context.allowedLeaseGenerations.at(-1)!,fencingToken:context.allowedFencingTokens.at(-1)!,cancellationSequence:context.cancellationSequence,runtimeEventSequence,terminalState,issuedBy:"fake-agent-runtime/v1",issuerEnvironment:context.environment==="TEST"?"TEST":"DEVELOPMENT",observedAt:this.now().toISOString(),verificationMethod:"FAKE_DETERMINISTIC_V1",attestationPayload,attestationPayloadDigest:runtimeTerminationAttestationPayloadDigest(attestationPayload)};const terminationEvidence={...claims,evidenceDigest:runtimeTerminationEvidenceDigest(claims)};return{...status,terminationEvidence};}
}
