import { describe,expect,it } from "vitest";
import { canonicalAgentOperationDigest, FakeAgentRuntime, SchemaValidationError, parseAgentResult, parseAgentTask, parseArtifact, parseDecision, parseFinding, parseProgress, type AgentRuntimeOperation, type AgentTask, type RuntimeCommand } from "./index.js";

const task=(scenario:AgentTask["scenario"],runId=`run/${scenario.toLowerCase()}`):AgentTask=>({schemaVersion:1,projectId:"project/1",taskId:"task/1",attemptId:"attempt/1",runId,role:scenario==="SECURITY_BLOCK"?"SECURITY":scenario==="LEGAL_COUNSEL_REQUIRED"?"LEGAL":"EXECUTOR",scenario,inputRef:"synthetic/input",repairOrdinal:0});
const command=(value:AgentTask,operation:AgentRuntimeOperation="startRun",fencingToken=1):RuntimeCommand=>({runId:value.runId,projectId:value.projectId,taskId:value.taskId,attemptId:value.attemptId,idempotencyKey:`${operation}:${fencingToken}`,requestDigest:canonicalAgentOperationDigest(operation,value),fencingToken,task:value});

describe("agent runtime schemas",()=>{
  it("validates all six closed versioned schemas fail-closed",()=>{
    const item=task("SUCCESS");expect(parseAgentTask(item)).toEqual(item);
    const runtime=new FakeAgentRuntime({now:()=>new Date("2026-01-01T00:00:00.000Z")});
    return runtime.startRun(command(item)).then(status=>{const result=status.result!;expect(parseAgentResult(result)).toEqual(result);expect(parseArtifact(result.artifacts[0])).toEqual(result.artifacts[0]);expect(parseProgress(status.progress[0])).toEqual(status.progress[0]);
      expect(()=>parseAgentTask({...item,extra:true})).toThrow(SchemaValidationError);expect(()=>parseAgentTask({...item,schemaVersion:2})).toThrow();expect(()=>parseAgentTask({...item,role:"OWNER"})).toThrow();expect(()=>parseAgentResult({...result,status:"SUCCESS",artifacts:[]})).toThrow();
      expect(()=>parseFinding({schemaVersion:1,findingId:"finding/1",category:"LEGAL",severity:"HIGH",status:"BLOCK",evidenceRef:"evidence/1"})).toThrow();expect(()=>parseDecision({schemaVersion:1,decisionId:"decision/1",kind:"QUALITY",outcome:"COUNSEL_REQUIRED",rationaleRef:"rationale/1"})).toThrow();});
  });
  it("rejects stop signals on ordinary results and mixed stop types",async()=>{const value=task("SECURITY_BLOCK");const result=(await new FakeAgentRuntime().startRun(command(value))).result!;expect(()=>parseAgentResult({...result,status:"SUCCESS",artifacts:[{schemaVersion:1,artifactId:"artifact/1",kind:"REPORT",objectRef:"object/1",digest:"a".repeat(64)}]})).toThrow();expect(()=>parseAgentResult({...result,findings:[...result.findings,{schemaVersion:1,findingId:"finding/legal",category:"LEGAL",severity:"HIGH",status:"COUNSEL_REQUIRED",evidenceRef:"evidence/legal"}],decisions:[...result.decisions,{schemaVersion:1,decisionId:"decision/legal",kind:"LEGAL",outcome:"COUNSEL_REQUIRED",rationaleRef:"rationale/legal"}]})).toThrow();});
});

describe("FakeAgentRuntime",()=>{
  it.each([["SUCCESS","SUCCEEDED","SUCCESS"],["ERROR","FAILED","ERROR"],["TIMEOUT","TIMED_OUT","TIMEOUT"],["SECURITY_BLOCK","BLOCKED","SECURITY_BLOCK"],["LEGAL_COUNSEL_REQUIRED","BLOCKED","LEGAL_COUNSEL_REQUIRED"]] as const)("simulates %s deterministically",async(scenario,state,resultStatus)=>{const value=task(scenario);const runtime=new FakeAgentRuntime({now:()=>new Date("2026-01-01T00:00:00.000Z")});const result=await runtime.startRun(command(value));expect(result).toMatchObject({state,terminal:true,result:{status:resultStatus}});expect(result.progress.map(item=>item.sequence)).toEqual(result.progress.map((_,index)=>index+1));expect(result.progress.at(-1)?.phase).toBe("FINISHED");expect(await runtime.startRun(command(value))).toEqual(result);});
  it("rejects invalid output rather than returning success",async()=>{const value=task("INVALID_OUTPUT");await expect(new FakeAgentRuntime().startRun(command(value))).rejects.toBeInstanceOf(SchemaValidationError);});
  it("retries the same run and attempt without changing repair ordinal",async()=>{const value=task("RETRY");const runtime=new FakeAgentRuntime({retryLimit:1});const first=await runtime.startRun(command(value));expect(first).toMatchObject({state:"RETRY_PENDING",retryCount:0,terminal:false});const second=await runtime.continueRun(command(value,"continueRun"));expect(second).toMatchObject({state:"SUCCEEDED",retryCount:1,result:{status:"SUCCESS"}});expect(value.repairOrdinal).toBe(0);});
  it("confirms cancellation and emits no progress after terminal",async()=>{const value=task("CANCEL");const runtime=new FakeAgentRuntime();await runtime.startRun(command(value));const cancelled=await runtime.cancelRun(command(value,"cancelRun"));expect(cancelled).toMatchObject({state:"CANCELLED",result:{status:"CANCELLED"}});const status=await runtime.getRunStatus(command(value,"getRunStatus"));expect(status.progress).toEqual(cancelled.progress);});
  it("rejects semantic divergence and stale fences while reconciling a higher fence",async()=>{const value=task("CANCEL");const runtime=new FakeAgentRuntime();await runtime.startRun(command(value));for(const mutation of [{role:"QA"},{scenario:"ERROR"},{inputRef:"synthetic/other"},{repairOrdinal:1}] as const){const changed={...value,...mutation} as AgentTask;await expect(runtime.getRunStatus({...command(changed,"getRunStatus"),runId:value.runId,taskId:value.taskId,attemptId:value.attemptId,projectId:value.projectId})).rejects.toThrow();}await runtime.startRun(command(value,"startRun",2));await expect(runtime.getRunStatus(command(value,"getRunStatus",1))).rejects.toThrow(/FENCE/);const wrong:RuntimeCommand={...command(value,"getRunStatus",2),taskId:"task/other"};await expect(runtime.getRunStatus(wrong)).rejects.toThrow(/INVALID|BINDING/);});
});
