import { describe,expect,it } from "vitest";
import { DefaultRuntimeTerminationEvidenceVerifier,runtimeTerminationAttestationPayloadDigest,runtimeTerminationEvidenceDigest,type RuntimeTerminationEvidenceCandidate,type RuntimeTerminationExpectedContext } from "./index.js";

const now="2026-07-14T12:00:00.000Z";
const claims=():Omit<RuntimeTerminationEvidenceCandidate,"evidenceDigest">=>{const attestationPayload={format:"FAKE_DETERMINISTIC_V1" as const,terminalState:"CANCELLED" as const,workloadId:"workload-1",startOperationId:"start-1",runtimeEventSequence:9};return{schemaVersion:1,evidenceId:"evidence-1",evidenceType:"FAKE_RUNTIME_TERMINATION",projectId:"project-1",runtimeId:"runtime-1",agentRunId:"run-1",attemptId:"attempt-1",jobId:"job-1",cancellationRequestId:"cancel-1",startOperationId:"start-1",workloadId:"workload-1",processIdentity:null,leaseGeneration:7,fencingToken:11,cancellationSequence:41,runtimeEventSequence:9,terminalState:"CANCELLED",issuedBy:"fake-agent-runtime/v1",issuerEnvironment:"DEVELOPMENT",observedAt:now,verificationMethod:"FAKE_DETERMINISTIC_V1",attestationPayload,attestationPayloadDigest:runtimeTerminationAttestationPayloadDigest(attestationPayload)};};
const candidate=(overrides:Partial<RuntimeTerminationEvidenceCandidate>={}):RuntimeTerminationEvidenceCandidate=>{const base={...claims(),...overrides};return{...base,evidenceDigest:overrides.evidenceDigest??runtimeTerminationEvidenceDigest(base)};};
const context=(overrides:Partial<RuntimeTerminationExpectedContext>={}):RuntimeTerminationExpectedContext=>({projectId:"project-1",runtimeId:"runtime-1",agentRunId:"run-1",attemptId:"attempt-1",jobId:"job-1",cancellationRequestId:"cancel-1",startOperationId:"start-1",workloadId:"workload-1",processIdentity:null,allowedLeaseGenerations:[7],allowedFencingTokens:[11],cancellationSequence:41,minimumRuntimeEventSequence:9,environment:"DEVELOPMENT",policyVersion:"cancellation-contract-1",verifierIdentity:"verifier/v1",now,maximumAgeMs:60_000,trustedIssuers:["fake-agent-runtime/v1"],supportedMethods:["FAKE_DETERMINISTIC_V1"],...overrides});
const verify=(item:RuntimeTerminationEvidenceCandidate,expected=context())=>new DefaultRuntimeTerminationEvidenceVerifier().verify(item,expected);

describe("RuntimeTerminationEvidenceVerifier (AT-09 bis AT-14, AT-22)",()=>{
  it("AT-09 accepts fully bound DEVELOPMENT_ONLY evidence",()=>{expect(verify(candidate())).toMatchObject({validity:"VALID",rejectionReason:null,idempotentReplay:false});});
  it.each([
    ["PROJECT_SCOPE_MISMATCH",{projectId:"other"}], ["RUNTIME_SCOPE_MISMATCH",{runtimeId:"other"}], ["AGENT_RUN_SCOPE_MISMATCH",{agentRunId:"other"}],
    ["JOB_SCOPE_MISMATCH",{jobId:"other"}], ["CANCELLATION_SCOPE_MISMATCH",{cancellationRequestId:"other"}],
    ["LEASE_GENERATION_MISMATCH",{leaseGeneration:6}], ["FENCING_TOKEN_MISMATCH",{fencingToken:10}],
  ] as const)("AT-13 rejects %s",(reason,change)=>expect(verify(candidate(change))).toMatchObject({validity:"REJECTED",rejectionReason:reason}));
  it("AT-13 rejects WORKLOAD_SCOPE_MISMATCH with an internally bound attestation",()=>{const attestationPayload={...claims().attestationPayload,workloadId:"other"};expect(verify(candidate({workloadId:"other",attestationPayload,attestationPayloadDigest:runtimeTerminationAttestationPayloadDigest(attestationPayload)}))).toMatchObject({validity:"REJECTED",rejectionReason:"WORKLOAD_SCOPE_MISMATCH"});});
  it("AT-11 rejects manipulated evidence and invalid digest",()=>expect(verify({...candidate(),terminalState:"EXITED"})).toMatchObject({validity:"REJECTED",rejectionReason:"DIGEST_MISMATCH"}));
  it("AT-12 rejects stale evidence",()=>expect(verify(candidate({observedAt:"2026-07-14T11:00:00.000Z"}))).toMatchObject({validity:"REJECTED",rejectionReason:"STALE"}));
  it("rejects unknown issuers and unsupported verification methods",()=>{expect(verify(candidate({issuedBy:"unknown"}))).toMatchObject({rejectionReason:"UNTRUSTED_ISSUER"});expect(verify(candidate({verificationMethod:"SIGNED_RUNTIME_ATTESTATION_V1"}))).toMatchObject({rejectionReason:"UNSUPPORTED_METHOD"});});
  it("AT-14 returns an idempotent same-scope decision and rejects cross-scope replay",()=>{const item=candidate();const prior={evidenceId:item.evidenceId,evidenceDigest:item.evidenceDigest,scopeKey:[item.projectId,item.runtimeId,item.agentRunId,item.attemptId,item.jobId,item.cancellationRequestId,item.startOperationId,item.workloadId??"",item.processIdentity??""].join("\0"),validity:"VALID" as const,consumed:true};expect(verify(item,context({priorEvidence:prior}))).toMatchObject({validity:"VALID",idempotentReplay:true});expect(verify(candidate({jobId:"other"}),context({priorEvidence:prior}))).toMatchObject({validity:"REJECTED",rejectionReason:"REPLAYED"});});
  it("AT-22 never accepts fake evidence for RELEASE_CANDIDATE or PRODUCTION",()=>{for(const environment of ["RELEASE_CANDIDATE","PRODUCTION"] as const)expect(verify(candidate(),context({environment}))).toMatchObject({validity:"REJECTED",rejectionReason:"ENVIRONMENT_NOT_ALLOWED"});});
  it("AT-22 WORKLOAD_NOT_CREATED uses the regular verifier and rejects wrong operation, scope, fence, replay, tampering and environment",()=>{const attestationPayload={format:"FAKE_DETERMINISTIC_V1" as const,terminalState:"NOT_CREATED" as const,workloadId:null,startOperationId:"start-1",runtimeEventSequence:9};const base=claims();const negative=candidate({...base,evidenceId:"not-created-1",evidenceType:"WORKLOAD_NOT_CREATED",startOperationId:"start-1",workloadId:null,processIdentity:null,terminalState:"NOT_CREATED",attestationPayload,attestationPayloadDigest:runtimeTerminationAttestationPayloadDigest(attestationPayload)});expect(verify(negative)).toMatchObject({validity:"VALID"});expect(verify(negative,context({startOperationId:"start-other"}))).toMatchObject({validity:"REJECTED",rejectionReason:"WORKLOAD_SCOPE_MISMATCH"});expect(verify({...negative,evidenceDigest:"0".repeat(64)})).toMatchObject({validity:"REJECTED",rejectionReason:"DIGEST_MISMATCH"});expect(verify(candidate({...negative,jobId:"other"}))).toMatchObject({validity:"REJECTED",rejectionReason:"JOB_SCOPE_MISMATCH"});expect(verify(candidate({...negative,agentRunId:"other"}))).toMatchObject({validity:"REJECTED",rejectionReason:"AGENT_RUN_SCOPE_MISMATCH"});expect(verify(candidate({...negative,cancellationRequestId:"other"}))).toMatchObject({validity:"REJECTED",rejectionReason:"CANCELLATION_SCOPE_MISMATCH"});expect(verify(candidate({...negative,leaseGeneration:6}))).toMatchObject({validity:"REJECTED",rejectionReason:"LEASE_GENERATION_MISMATCH"});expect(verify(candidate({...negative,fencingToken:10}))).toMatchObject({validity:"REJECTED",rejectionReason:"FENCING_TOKEN_MISMATCH"});expect(verify(negative,context({environment:"PRODUCTION"}))).toMatchObject({validity:"REJECTED",rejectionReason:"ENVIRONMENT_NOT_ALLOWED"});});
  it.each([["evidenceType","UNKNOWN_EVIDENCE"],["issuerEnvironment","UNKNOWN_ENVIRONMENT"],["verificationMethod","UNKNOWN_METHOD"],["terminalState","UNKNOWN_STATE"]] as const)("rejects an unknown closed-set %s as malformed",(field,value)=>expect(verify(candidate({[field]:value} as unknown as Partial<RuntimeTerminationEvidenceCandidate>))).toMatchObject({validity:"REJECTED",rejectionReason:"MALFORMED"}));
  it("rejects attestation payload or payload digest manipulation",()=>{const item=candidate();expect(verify({...item,attestationPayload:{...item.attestationPayload,terminalState:"EXITED"}})).toMatchObject({validity:"REJECTED",rejectionReason:"DIGEST_MISMATCH"});expect(verify({...item,attestationPayloadDigest:"0".repeat(64)})).toMatchObject({validity:"REJECTED",rejectionReason:"DIGEST_MISMATCH"});});
  it("rejects unimplemented type/method compatibility combinations",()=>{expect(verify(candidate({evidenceType:"PROCESS_EXIT_ATTESTATION"}))).toMatchObject({validity:"REJECTED",rejectionReason:"UNSUPPORTED_METHOD"});expect(verify(candidate({verificationMethod:"LOCAL_PROCESS_ATTESTATION_V1"}),context({supportedMethods:["LOCAL_PROCESS_ATTESTATION_V1"]}))).toMatchObject({validity:"REJECTED",rejectionReason:"UNSUPPORTED_METHOD"});});
});
