import { randomUUID } from "node:crypto";
import { Pool } from "pg";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import type { ProjectId } from "@software-builder/core";
import { AgentRegistryService,DEVELOPMENT_AGENT_SEEDS,HmacCapabilityAuthority,PostgresDatabase,PostgresProjectContextIssuer,seedDevelopmentAgentRegistry } from "./index.js";
import { migrate,resetDatabase } from "./migrations.js";

const adminUrl=process.env.TEST_DATABASE_URL;
const waitForDatabaseQuiescence=async(pool:Pool,timeoutMs=5_000)=>{const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){const active=await pool.query<{count:string}>("SELECT count(*) count FROM pg_stat_activity WHERE datname=current_database() AND pid<>pg_backend_pid()");if(Number(active.rows[0]!.count)===0)return;await new Promise(resolve=>setTimeout(resolve,5));}throw new Error("Timed out waiting for test database quiescence");};

describe("Agent Registry PostgreSQL integration",()=>{
  let admin:Pool;let db:PostgresDatabase;let authority:HmacCapabilityAuthority;let runtimeUrl:string;let contextUrl:string;let capability:ReturnType<HmacCapabilityAuthority["issueProject"]>;let service:AgentRegistryService;
  beforeAll(async()=>{
    if(!adminUrl)throw new Error("TEST_DATABASE_URL ist fuer Agent-Registry-Integration verpflichtend; Skips sind nicht zulaessig.");
    const parsed=new URL(adminUrl);if(!parsed.pathname.toLowerCase().endsWith("_test"))throw new Error("TEST_DATABASE_URL muss auf _test enden.");
    admin=new Pool({connectionString:adminUrl});await waitForDatabaseQuiescence(admin);await resetDatabase(admin,{connectionString:adminUrl,environment:"test"});expect(await migrate(admin)).toEqual([]);
    await admin.query("SELECT builder.provision_runtime_password('registry-integration-only-123')");await admin.query("SELECT builder.provision_context_password('registry-context-integration-only-123')");
    parsed.username="builder_app_login";parsed.password="registry-integration-only-123";runtimeUrl=parsed.toString();const context=new URL(parsed);context.username="builder_context_login";context.password="registry-context-integration-only-123";contextUrl=context.toString();
    authority=new HmacCapabilityAuthority();const issuer=await PostgresProjectContextIssuer.connect(contextUrl);db=await PostgresDatabase.connectRuntime(runtimeUrl,issuer,authority,authority);
    const projectId=randomUUID() as ProjectId;await db.projects.create(authority.issueBootstrap("registry-test","INTEGRATION_TEST"),{id:projectId,status:"PLANNING"},{actorScope:"INTEGRATION_TEST",actorIdentityId:"registry-test",idempotencyKey:`project-${projectId}`,requestDigest:"a".repeat(64),aggregateType:"PROJECT",aggregateId:projectId,transition:"CREATE",newState:"PLANNING",reasonCode:"SYNTHETIC_TEST",policyVersion:"test-1",eventType:"PROJECT_CREATED",schemaVersion:1});
    capability=authority.issueProject(projectId,{subject:"registry-test",actorScope:"INTEGRATION_TEST",allowedRoles:["INTEGRATION_TEST"],allowedOperations:["agent_registry:read","agent_registry:append"]},120_000);service=new AgentRegistryService(db.agentRegistry);
  },30_000);
  afterAll(async()=>{await db?.close();if(admin){await admin.end();const cleanup=new Pool({connectionString:adminUrl!});try{await waitForDatabaseQuiescence(cleanup);await resetDatabase(cleanup,{connectionString:adminUrl!,environment:"test"});}finally{await cleanup.end();}}},30_000);

  const create=async(agentKey:string,version=1)=>service.createDefinition(capability,{agentKey,displayName:agentKey,role:"PLANNER",description:"Synthetic integration definition.",version,instructions:"Plan only the scoped synthetic development task.",allowedCapabilities:["documentation.read"],forbiddenCapabilities:["production.deploy"],modelConfiguration:{model:"development-model",reasoningLevel:"LOW",timeoutMs:1000,maxAttempts:1},createdBy:"synthetic-integration-test"});

  it("persistiert alle acht Development-Seeds und listet sie nach Rolle oder Status",async()=>{await seedDevelopmentAgentRegistry(service,capability);expect(await service.list(capability,{status:"DRAFT"})).toHaveLength(8);expect((await service.list(capability,{role:"LEGAL_DE_EU"})).map(item=>item.agentKey)).toEqual(["legal-de-eu"]);expect(DEVELOPMENT_AGENT_SEEDS).toHaveLength(8);});
  it("erstellt und liest unveraenderliche Versionen mit stabiler agentId",async()=>{const first=await create("versioned-agent");const second=await service.createVersion(capability,{agentKey:first.agentKey,displayName:"Version two",role:"PLANNER",description:"Synthetic second version.",version:2,instructions:"Plan the second synthetic definition.",allowedCapabilities:["documentation.read"],forbiddenCapabilities:["production.deploy"],createdBy:"synthetic-integration-test"});expect(second.agentId).toBe(first.agentId);expect((await service.getVersion(capability,first.agentKey,1))?.instructions).toBe(first.instructions);await expect(admin.query("UPDATE builder.agent_registry_versions SET instructions='mutated' WHERE id=$1",[first.id])).rejects.toThrow(/immutable/);});
  it("laesst bei paralleler Erstellung derselben Version genau einen Erfolg zu",async()=>{const first=await create("duplicate-agent");const input={agentKey:first.agentKey,displayName:"Duplicate candidate",role:"PLANNER" as const,description:"Synthetic duplicate candidate.",version:2,instructions:"Plan the duplicate version test.",allowedCapabilities:["documentation.read"],forbiddenCapabilities:["production.deploy"],createdBy:"synthetic-integration-test"};const results=await Promise.allSettled([service.createVersion(capability,input),service.createVersion(capability,input)]);expect(results.filter(result=>result.status==="fulfilled")).toHaveLength(1);expect(results.filter(result=>result.status==="rejected")).toHaveLength(1);expect(await service.getVersion(capability,first.agentKey,2)).toBeDefined();});
  it("linearisiert parallele Aktivierungen auf genau eine ACTIVE-Version",async()=>{const first=await create("activation-agent");for(const version of [2,3])await service.createVersion(capability,{agentKey:first.agentKey,displayName:`Version ${version}`,role:"PLANNER",description:"Synthetic activation candidate.",version,instructions:`Plan synthetic version ${version}.`,allowedCapabilities:["documentation.read"],forbiddenCapabilities:["production.deploy"],createdBy:"synthetic-integration-test"});const results=await Promise.allSettled([service.activate(capability,first.agentKey,2),service.activate(capability,first.agentKey,3)]);expect(results.every(result=>result.status==="fulfilled")).toBe(true);const active=await service.list(capability,{status:"ACTIVE"});expect(active.filter(item=>item.agentKey===first.agentKey)).toHaveLength(1);expect([2,3]).toContain((await service.getActive(capability,first.agentKey))?.version);});
  it("rollt eine fehlgeschlagene Aktivierung ohne Teilzustand zurueck und reaktiviert RETIRED nie",async()=>{const first=await create("rollback-agent");await service.activate(capability,first.agentKey,1);await expect(service.activate(capability,first.agentKey,999)).rejects.toThrow(/unbekannt/);expect((await service.getActive(capability,first.agentKey))?.version).toBe(1);await service.retireActive(capability,first.agentKey);await expect(service.activate(capability,first.agentKey,1)).rejects.toThrow(/RETIRED/);expect(await service.getActive(capability,first.agentKey)).toBeUndefined();});
  it("liest persistierte Definitionen nach Repository-Neuinstanziierung",async()=>{const stored=await create("restart-agent");const issuer=await PostgresProjectContextIssuer.connect(contextUrl);const restarted=await PostgresDatabase.connectRuntime(runtimeUrl,issuer,authority,authority);try{const restartedService=new AgentRegistryService(restarted.agentRegistry);expect((await restartedService.getVersion(capability,stored.agentKey,stored.version))?.id).toBe(stored.id);}finally{await restarted.close();}});
  it("erzwingt Status-, Rollen-, Eindeutigkeits- und Secret-Constraints auch in PostgreSQL",async()=>{await expect(admin.query("INSERT INTO builder.agent_registry_versions(agent_id,agent_key,display_name,role,description,version,revision,status,instructions,created_by) VALUES(gen_random_uuid(),'invalid-db','Invalid','UNKNOWN','Synthetic',1,1,'DRAFT','Synthetic instructions','synthetic-test')")).rejects.toThrow();await expect(admin.query("INSERT INTO builder.agent_registry_versions(agent_id,agent_key,display_name,role,description,version,revision,status,instructions,model_config,created_by) VALUES(gen_random_uuid(),'secret-db','Invalid','PLANNER','Synthetic',1,1,'DRAFT','api_key=not-allowed',$1::jsonb,'synthetic-test')",[JSON.stringify({apiKey:"placeholder"})])).rejects.toThrow();});
});
