import { createHash, randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { canonicalAgentOperationDigest, parseAgentResult, parseAgentTask, parseProgress, type AgentResult, type AgentTask, type Progress } from "@software-builder/agent-runtime";

export type AgentJobStatus="PENDING"|"CLAIMED"|"RUNNING"|"RETRY_SCHEDULED"|"SUCCEEDED"|"FAILED"|"CANCELLED"|"DEAD_LETTER"|"CANCELLING"|"CANCEL_STUCK";
export type CancellationAttemptOutcome="FAILED"|"TIMED_OUT"|"REJECTED";
export type CancellationConfirmationKind="RUNTIME_CANCEL_CONFIRMED"|"RUNTIME_STATUS_CANCELLED"|"RUNTIME_TERMINAL_OBSERVED"|"PROCESS_TERMINATED"|"RECOVERY_CONFIRMED";
export interface AgentJobClaim { readonly jobId:string;readonly projectId:string;readonly task:AgentTask;readonly workerId:string;readonly claimId:string;readonly fencingToken:number;readonly leaseExpiresAt:Date;readonly retryCount:number;readonly maxRetries:number;readonly cancelRequested:boolean;readonly cancelAttemptCount:number;readonly cancelMaxAttempts:number;readonly cancelLastOutcome:CancellationAttemptOutcome|"CONFIRMED"|null;readonly cancelLastErrorCode:string|null;readonly cancelConfirmedAt:Date|null;readonly cancelConfirmationKind:CancellationConfirmationKind|null; }
export interface AgentJobGuard { readonly jobId:string;readonly workerId:string;readonly claimId:string;readonly fencingToken:number; }
export interface EnqueueAgentJob { readonly task:AgentTask;readonly messageId:string;readonly consumerIdentity:string;readonly idempotencyKey:string;readonly requestDigest:string;readonly traceId:string;readonly maxRetries:number; }
export interface AgentJobStatusView { readonly jobId:string;readonly projectId:string;readonly runId:string;readonly status:AgentJobStatus;readonly retryCount:number;readonly maxRetries:number;readonly fencingToken:number|null;readonly result:AgentResult|null;readonly cancelRequested:boolean;readonly cancelAttemptCount:number;readonly cancelMaxAttempts:number;readonly cancelLastOutcome:CancellationAttemptOutcome|"CONFIRMED"|null;readonly cancelLastErrorCode:string|null;readonly cancelConfirmedAt:Date|null;readonly cancelConfirmationKind:CancellationConfirmationKind|null; }
type Queryable=Pick<Pool,"connect"|"query">;
interface JobRow { id:string;project_id:string;status:AgentJobStatus;retry_count:number;max_retries:number;lease_owner:string|null;claim_idempotency_key:string|null;fencing_token:string|null;lease_expires_at:Date|null;cancel_requested_at:Date|null;cancel_attempt_count:number;cancel_max_attempts:number;cancel_last_outcome:CancellationAttemptOutcome|"CONFIRMED"|null;cancel_last_error_code:string|null;cancel_confirmed_at:Date|null;cancel_confirmation_kind:CancellationConfirmationKind|null;agent_run_id:string;agent_attempt_id:string;result_payload:unknown|null;schema_version:number;task_id:string;attempt_id:string;run_id:string;role:AgentTask["role"];scenario:AgentTask["scenario"];input_ref:string;repair_ordinal:number; }

export class AgentJobLeaseLostError extends Error { readonly code="AGENT_JOB_LEASE_LOST";constructor(){super("Agent job lease is no longer owned by this claim and fence");this.name="AgentJobLeaseLostError";} }
export class AgentJobCancellationRequestedError extends Error { readonly code="AGENT_JOB_CANCELLATION_REQUESTED";constructor(){super("Agent job cancellation has priority over further work");this.name="AgentJobCancellationRequestedError";} }

export class AgentJobRepository {
  constructor(private readonly pool:Queryable) {}
  async enqueue(input:EnqueueAgentJob):Promise<{jobId:string;duplicate:boolean}>{
    const task=parseAgentTask(input.task);this.assertEnqueue(input);return this.tx(async client=>{
      const inbox=await client.query("INSERT INTO builder.inbox_events(project_id,consumer_identity,message_id,status,semantic_digest) VALUES($1,$2,$3,'PROCESSING',$4) ON CONFLICT(consumer_identity,message_id) DO NOTHING RETURNING id",[task.projectId,input.consumerIdentity,input.messageId,input.requestDigest]);
      if(!inbox.rowCount){const existing=await client.query<{id:string;request_digest:string;semantic_digest:string|null}>("SELECT job.id,task.request_digest,inbox.semantic_digest FROM builder.background_jobs job JOIN builder.agent_runtime_tasks task ON task.project_id=job.project_id AND task.run_id=job.agent_run_id JOIN builder.inbox_events inbox ON inbox.project_id=job.project_id AND inbox.consumer_identity=$3 AND inbox.message_id=$4 WHERE job.project_id=$1 AND job.idempotency_key=$2",[task.projectId,input.idempotencyKey,input.consumerIdentity,input.messageId]);const prior=existing.rows[0];if(!prior)throw new Error("INBOX_REPLAY_WITHOUT_JOB");if(prior.request_digest!==input.requestDigest||prior.semantic_digest!==input.requestDigest)throw new Error("INBOX_REPLAY_DIVERGED");return{jobId:prior.id,duplicate:true};}
      await client.query("INSERT INTO builder.agent_runtime_tasks(project_id,task_id,attempt_id,run_id,schema_version,role,scenario,input_ref,repair_ordinal,request_digest) VALUES($1,$2,$3,$4,1,$5,$6,$7,$8,$9)",[task.projectId,task.taskId,task.attemptId,task.runId,task.role,task.scenario,task.inputRef,task.repairOrdinal,input.requestDigest]);
      await client.query("INSERT INTO builder.agent_runtime_runs(project_id,run_id,task_id,attempt_id,state) VALUES($1,$2,$3,$4,'QUEUED')",[task.projectId,task.runId,task.taskId,task.attemptId]);
      const job=await client.query<{id:string}>("INSERT INTO builder.background_jobs(project_id,job_type,aggregate_type,aggregate_id,schema_version,policy_version,idempotency_key,expected_aggregate_version,trace_id,status,max_retries,agent_run_id,agent_attempt_id) VALUES($1,'AGENT_RUNTIME','AGENT_RUN',$2,1,'worker-fake-runtime-1',$3,1,$4,'PENDING',$5,$6,$7) RETURNING id",[task.projectId,randomUUID(),input.idempotencyKey,input.traceId,input.maxRetries,task.runId,task.attemptId]);
      const jobId=job.rows[0]!.id;await this.audit(client,task.projectId,jobId,"ENQUEUED",null,{runId:task.runId});await this.outbox(client,task.projectId,jobId,"AGENT_JOB_ENQUEUED",`${input.idempotencyKey}:enqueued`);
      await client.query("UPDATE builder.inbox_events SET status='PROCESSED',processed_at=clock_timestamp() WHERE project_id=$1 AND consumer_identity=$2 AND message_id=$3",[task.projectId,input.consumerIdentity,input.messageId]);return{jobId,duplicate:false};
    });
  }
  async claimNext(workerId:string,claimId:string,leaseMs:number):Promise<AgentJobClaim|null>{this.assertOwner(workerId,claimId,leaseMs);return this.tx(async client=>{
    const selected=await client.query<JobRow>(`SELECT job.id,job.project_id,job.status,job.retry_count,job.max_retries,job.lease_owner,job.claim_idempotency_key,job.fencing_token,job.lease_expires_at,job.cancel_requested_at,job.cancel_attempt_count,job.cancel_max_attempts,job.cancel_last_outcome,job.cancel_last_error_code,job.cancel_confirmed_at,job.cancel_confirmation_kind,job.agent_run_id,job.agent_attempt_id,NULL::jsonb result_payload,
      task.schema_version,task.task_id,task.attempt_id,task.run_id,task.role,task.scenario,task.input_ref,task.repair_ordinal
      FROM builder.background_jobs job JOIN builder.agent_runtime_tasks task ON task.project_id=job.project_id AND task.run_id=job.agent_run_id
      WHERE job.job_type='AGENT_RUNTIME' AND job.available_at<=clock_timestamp() AND (job.status IN ('PENDING','RETRY_SCHEDULED') OR (job.status='CANCELLING' AND job.lease_owner IS NULL) OR (job.status IN ('CLAIMED','RUNNING','CANCELLING') AND job.lease_expires_at<=clock_timestamp()))
      ORDER BY job.available_at,job.created_at,job.id FOR UPDATE OF job SKIP LOCKED LIMIT 1`);
    const row=selected.rows[0];if(!row)return null;const now=await this.databaseNow(client);const reclaim=["CLAIMED","RUNNING","CANCELLING"].includes(row.status);
    const fence=await client.query<{last_fencing_token:string}>("INSERT INTO builder.workflow_fence_counters(project_id,last_fencing_token) VALUES($1,1) ON CONFLICT(project_id) DO UPDATE SET last_fencing_token=builder.workflow_fence_counters.last_fencing_token+1 RETURNING last_fencing_token",[row.project_id]);
    const fencingToken=Number(fence.rows[0]!.last_fencing_token);const updated=await client.query<{lease_expires_at:Date}>("UPDATE builder.background_jobs SET status='CLAIMED',claimed_at=$7::timestamptz,claimed_by=$2::builder.opaque_ref,lease_owner=$2::text,claim_idempotency_key=$3::text,lease_expires_at=$7::timestamptz+$4::double precision*interval '1 millisecond',fencing_token=$5,heartbeat_at=$7::timestamptz WHERE project_id=$1 AND id=$6 RETURNING lease_expires_at",[row.project_id,workerId,claimId,leaseMs,fencingToken,row.id,now]);
    await client.query("UPDATE builder.agent_runtime_runs SET state=CASE WHEN state='QUEUED' THEN 'RUNNING' ELSE state END WHERE project_id=$1 AND run_id=$2",[row.project_id,row.run_id]);await this.audit(client,row.project_id,row.id,reclaim?"RECLAIMED":"CLAIMED",fencingToken,{workerId,claimId});
    return this.mapClaim({...row,status:"CLAIMED",lease_owner:workerId,claim_idempotency_key:claimId,fencing_token:String(fencingToken),lease_expires_at:updated.rows[0]!.lease_expires_at});
  });}
  async loadClaim(guard:AgentJobGuard):Promise<AgentJobClaim>{return this.tx(async client=>this.loadOwned(client,guard,true));}
  async heartbeat(guard:AgentJobGuard,leaseMs:number):Promise<AgentJobClaim>{if(!Number.isSafeInteger(leaseMs)||leaseMs<1)throw new Error("INVALID_LEASE");return this.tx(async client=>{const now=await this.lockOwned(client,guard,true);const row=await client.query<{lease_expires_at:Date}>("UPDATE builder.background_jobs SET heartbeat_at=$6::timestamptz,lease_expires_at=$6::timestamptz+$5::double precision*interval '1 millisecond' WHERE id=$1 AND lease_owner=$2 AND claim_idempotency_key=$3 AND fencing_token=$4 RETURNING lease_expires_at",[guard.jobId,guard.workerId,guard.claimId,guard.fencingToken,leaseMs,now]);if(!row.rowCount)throw new AgentJobLeaseLostError();const claim=await this.loadOwned(client,guard,false);await this.audit(client,claim.projectId,guard.jobId,"HEARTBEAT",guard.fencingToken,{});return{...claim,leaseExpiresAt:row.rows[0]!.lease_expires_at};});}
  async appendProgress(guard:AgentJobGuard,progress:Progress):Promise<void>{parseProgress(progress);await this.tx(async client=>{const claim=await this.loadOwned(client,guard,true);if(progress.runId!==claim.task.runId)throw new Error("PROGRESS_BINDING_MISMATCH");if(claim.cancelRequested&&!['CANCELLING','FINISHED'].includes(progress.phase))throw new AgentJobCancellationRequestedError();const max=await client.query<{sequence:number}>("SELECT coalesce(max(sequence),0)::int sequence FROM builder.agent_runtime_progress WHERE project_id=$1 AND run_id=$2",[claim.projectId,progress.runId]);if(progress.sequence<=max.rows[0]!.sequence){const prior=await client.query<{phase:string;occurred_at:Date}>("SELECT phase,occurred_at FROM builder.agent_runtime_progress WHERE project_id=$1 AND run_id=$2 AND sequence=$3",[claim.projectId,progress.runId,progress.sequence]);if(prior.rows[0]?.phase!==progress.phase||prior.rows[0].occurred_at.toISOString()!==new Date(progress.occurredAt).toISOString())throw new Error("PROGRESS_REPLAY_DIVERGED");return;}if(progress.sequence!==max.rows[0]!.sequence+1)throw new Error("PROGRESS_SEQUENCE_INVALID");await client.query("INSERT INTO builder.agent_runtime_progress(project_id,run_id,sequence,schema_version,phase,occurred_at) VALUES($1,$2,$3,1,$4,$5)",[claim.projectId,progress.runId,progress.sequence,progress.phase,progress.occurredAt]);await this.audit(client,claim.projectId,guard.jobId,"PROGRESS",guard.fencingToken,{sequence:progress.sequence,phase:progress.phase});});}
  async scheduleRetry(guard:AgentJobGuard,errorCode:string,delayMs:number):Promise<AgentJobStatusView>{if(!/^[A-Z][A-Z0-9_]{0,63}$/.test(errorCode)||!Number.isSafeInteger(delayMs)||delayMs<0)throw new Error("INVALID_RETRY");return this.tx(async client=>{const claim=await this.loadOwned(client,guard,true);const now=await this.databaseNow(client);const exhausted=claim.retryCount>=claim.maxRetries;const updated=await client.query("UPDATE builder.background_jobs SET status=$5,retry_count=retry_count+1,available_at=$6::timestamptz+$7::double precision*interval '1 millisecond',last_error_code=$8,lease_owner=NULL,claim_idempotency_key=NULL,lease_expires_at=NULL,terminal_at=CASE WHEN $5='DEAD_LETTER' THEN $6::timestamptz ELSE NULL END WHERE id=$1 AND lease_owner=$2 AND claim_idempotency_key=$3 AND fencing_token=$4",[guard.jobId,guard.workerId,guard.claimId,guard.fencingToken,exhausted?"DEAD_LETTER":"RETRY_SCHEDULED",now,delayMs,errorCode]);if(!updated.rowCount)throw new AgentJobLeaseLostError();await client.query("UPDATE builder.agent_runtime_runs SET state=$3,runtime_retry_count=runtime_retry_count+1,terminal_at=CASE WHEN $3='FAILED' THEN $4::timestamptz ELSE NULL END WHERE project_id=$1 AND run_id=$2",[claim.projectId,claim.task.runId,exhausted?"FAILED":"RETRY_PENDING",now]);await this.audit(client,claim.projectId,guard.jobId,exhausted?"RETRY_EXHAUSTED":"RETRY_SCHEDULED",guard.fencingToken,{errorCode});await this.outbox(client,claim.projectId,guard.jobId,exhausted?"AGENT_JOB_FAILED":"AGENT_JOB_RETRY",`${guard.jobId}:retry:${claim.retryCount+1}`);return this.getStatusWith(client,guard.jobId);});}
  async requestCancel(jobId:string):Promise<AgentJobStatusView>{return this.tx(async client=>{const row=await client.query<{project_id:string;status:AgentJobStatus;fencing_token:string|null;runtime_state:string;cancel_requested_at:Date|null}>("SELECT job.project_id,job.status,job.fencing_token,job.cancel_requested_at,run.state runtime_state FROM builder.background_jobs job JOIN builder.agent_runtime_runs run ON run.project_id=job.project_id AND run.run_id=job.agent_run_id WHERE job.id=$1 FOR UPDATE OF job",[jobId]);const job=row.rows[0];if(!job)throw new Error("AGENT_JOB_NOT_FOUND");const fence=job.fencing_token?Number(job.fencing_token):null;if(job.cancel_requested_at)return this.getStatusWith(client,jobId);if(["SUCCEEDED","FAILED","CANCELLED","DEAD_LETTER","CANCEL_STUCK"].includes(job.status)){await this.audit(client,job.project_id,jobId,"CANCEL_REJECTED",fence,{status:job.status,runtimeState:job.runtime_state});return this.getStatusWith(client,jobId);}const now=await this.databaseNow(client);await client.query("UPDATE builder.background_jobs SET cancel_requested_at=$2,status='CANCELLING' WHERE id=$1",[jobId,now]);await client.query("UPDATE builder.agent_runtime_runs SET state=CASE WHEN state IN ('QUEUED','RUNNING','RETRY_PENDING') THEN 'CANCELLATION_REQUESTED' ELSE state END WHERE project_id=$1 AND run_id=(SELECT agent_run_id FROM builder.background_jobs WHERE id=$2)",[job.project_id,jobId]);await this.audit(client,job.project_id,jobId,"CANCEL_REQUESTED",fence,{status:job.status});return this.getStatusWith(client,jobId);});}
  async beginCancellationAttempt(guard:AgentJobGuard):Promise<{started:true;attempt:number;maxAttempts:number}|{started:false;attempt:number;maxAttempts:number}>{return this.tx(async client=>{const claim=await this.loadOwned(client,guard,true);if(!claim.cancelRequested)throw new Error("CANCEL_NOT_REQUESTED");if(claim.cancelConfirmedAt)throw new Error("CANCEL_ALREADY_CONFIRMED");if(claim.cancelAttemptCount>=claim.cancelMaxAttempts){const now=await this.databaseNow(client);await client.query("UPDATE builder.background_jobs SET status='CANCEL_STUCK',last_error_code='CANCEL_RETRY_EXHAUSTED',cancel_last_error_code='CANCEL_RETRY_EXHAUSTED',lease_owner=NULL,claim_idempotency_key=NULL,lease_expires_at=NULL,terminal_at=$5::timestamptz WHERE id=$1 AND lease_owner=$2 AND claim_idempotency_key=$3 AND fencing_token=$4",[guard.jobId,guard.workerId,guard.claimId,guard.fencingToken,now]);await client.query("UPDATE builder.agent_runtime_runs SET state='BLOCKED',terminal_at=$3::timestamptz WHERE project_id=$1 AND run_id=$2 AND state NOT IN ('SUCCEEDED','FAILED','TIMED_OUT','CANCELLED','BLOCKED','SCHEMA_ERROR')",[claim.projectId,claim.task.runId,now]);await this.audit(client,claim.projectId,guard.jobId,"CANCEL_STUCK",guard.fencingToken,{attempt:claim.cancelAttemptCount,maxAttempts:claim.cancelMaxAttempts,errorCode:"CANCEL_RETRY_EXHAUSTED"});await this.outbox(client,claim.projectId,guard.jobId,"AGENT_JOB_CANCEL_STUCK",`${guard.jobId}:cancel-stuck`);return{started:false,attempt:claim.cancelAttemptCount,maxAttempts:claim.cancelMaxAttempts};}const now=await this.databaseNow(client);const updated=await client.query<{cancel_attempt_count:number;cancel_max_attempts:number}>("UPDATE builder.background_jobs SET status='CANCELLING',cancel_attempt_count=cancel_attempt_count+1,cancel_last_attempt_at=$5::timestamptz,cancel_last_outcome=NULL,cancel_last_error_code=NULL WHERE id=$1 AND lease_owner=$2 AND claim_idempotency_key=$3 AND fencing_token=$4 RETURNING cancel_attempt_count,cancel_max_attempts",[guard.jobId,guard.workerId,guard.claimId,guard.fencingToken,now]);if(!updated.rowCount)throw new AgentJobLeaseLostError();const attempt=updated.rows[0]!.cancel_attempt_count;const maxAttempts=updated.rows[0]!.cancel_max_attempts;await this.audit(client,claim.projectId,guard.jobId,"CANCEL_ATTEMPTED",guard.fencingToken,{attempt,maxAttempts});return{started:true,attempt,maxAttempts};});}
  async recordCancellationFailure(guard:AgentJobGuard,outcome:CancellationAttemptOutcome,errorCode:string,retryDelayMs:number):Promise<AgentJobStatusView>{if(!/^[A-Z][A-Z0-9_]{0,63}$/.test(errorCode)||!Number.isSafeInteger(retryDelayMs)||retryDelayMs<0)throw new Error("INVALID_CANCELLATION_FAILURE");return this.tx(async client=>{const claim=await this.loadOwned(client,guard,true);if(!claim.cancelRequested||claim.cancelAttemptCount<1)throw new Error("CANCEL_ATTEMPT_REQUIRED");const now=await this.databaseNow(client);const exhausted=claim.cancelAttemptCount>=claim.cancelMaxAttempts;const status=exhausted?"CANCEL_STUCK":"CANCELLING";const updated=await client.query("UPDATE builder.background_jobs SET status=$5,cancel_last_outcome=$6,cancel_last_error_code=$7,last_error_code=$7,available_at=$8::timestamptz+$9::double precision*interval '1 millisecond',lease_owner=NULL,claim_idempotency_key=NULL,lease_expires_at=NULL,terminal_at=CASE WHEN $5='CANCEL_STUCK' THEN $8::timestamptz ELSE NULL END WHERE id=$1 AND lease_owner=$2 AND claim_idempotency_key=$3 AND fencing_token=$4",[guard.jobId,guard.workerId,guard.claimId,guard.fencingToken,status,outcome,errorCode,now,retryDelayMs]);if(!updated.rowCount)throw new AgentJobLeaseLostError();await client.query("UPDATE builder.agent_runtime_runs SET state=CASE WHEN $3 THEN 'BLOCKED' ELSE 'CANCELLATION_REQUESTED' END,terminal_at=CASE WHEN $3 THEN $4::timestamptz ELSE NULL END WHERE project_id=$1 AND run_id=$2 AND state NOT IN ('SUCCEEDED','FAILED','TIMED_OUT','CANCELLED','BLOCKED','SCHEMA_ERROR')",[claim.projectId,claim.task.runId,exhausted,now]);await this.audit(client,claim.projectId,guard.jobId,"CANCEL_ATTEMPT_FAILED",guard.fencingToken,{attempt:claim.cancelAttemptCount,maxAttempts:claim.cancelMaxAttempts,outcome,errorCode});if(exhausted){await this.audit(client,claim.projectId,guard.jobId,"CANCEL_STUCK",guard.fencingToken,{attempt:claim.cancelAttemptCount,maxAttempts:claim.cancelMaxAttempts,errorCode});await this.outbox(client,claim.projectId,guard.jobId,"AGENT_JOB_CANCEL_STUCK",`${guard.jobId}:cancel-stuck`);}else await this.outbox(client,claim.projectId,guard.jobId,"AGENT_JOB_CANCEL_RETRY",`${guard.jobId}:cancel-retry:${claim.cancelAttemptCount}`);return this.getStatusWith(client,guard.jobId);});}
  async complete(guard:AgentJobGuard,result:AgentResult,messageId:string):Promise<AgentJobStatusView>{return this.finish(guard,result,messageId,"COMPLETED");}
  async fail(guard:AgentJobGuard,errorCode:string):Promise<AgentJobStatusView>{if(!/^[A-Z][A-Z0-9_]{0,63}$/.test(errorCode))throw new Error("INVALID_ERROR_CODE");return this.tx(async client=>{const claim=await this.loadOwned(client,guard,true);const now=await this.databaseNow(client);const state=errorCode==="AGENT_SCHEMA_INVALID"?"SCHEMA_ERROR":"FAILED";const updated=await client.query("UPDATE builder.background_jobs SET status='FAILED',last_error_code=$5,terminal_at=$6,lease_expires_at=NULL WHERE id=$1 AND lease_owner=$2 AND claim_idempotency_key=$3 AND fencing_token=$4",[guard.jobId,guard.workerId,guard.claimId,guard.fencingToken,errorCode,now]);if(!updated.rowCount)throw new AgentJobLeaseLostError();await client.query("UPDATE builder.agent_runtime_runs SET state=$3,terminal_at=$4 WHERE project_id=$1 AND run_id=$2",[claim.projectId,claim.task.runId,state,now]);await this.audit(client,claim.projectId,guard.jobId,errorCode==="AGENT_SCHEMA_INVALID"?"SCHEMA_REJECTED":"FAILED",guard.fencingToken,{errorCode});await this.outbox(client,claim.projectId,guard.jobId,"AGENT_JOB_FAILED",`${guard.jobId}:failed`);return this.getStatusWith(client,guard.jobId);});}
  async confirmCancelled(guard:AgentJobGuard,result:AgentResult,messageId:string,confirmationKind:CancellationConfirmationKind):Promise<AgentJobStatusView>{if(result.status!=="CANCELLED")throw new Error("CANCEL_RESULT_REQUIRED");return this.finish(guard,result,messageId,"CANCELLED",confirmationKind);}
  async getStatus(jobId:string):Promise<AgentJobStatusView>{return this.getStatusWith(this.pool,jobId);}
  async loadRuntimeSnapshot(guard:AgentJobGuard):Promise<unknown|undefined>{return this.tx(async client=>{const claim=await this.loadOwned(client,guard,true);const row=(await client.query<{runtime_snapshot:unknown;runtime_fencing_token:string}>("SELECT runtime_snapshot,runtime_fencing_token FROM builder.agent_runtime_runs WHERE project_id=$1 AND run_id=$2",[claim.projectId,claim.task.runId])).rows[0];if(!row||Number(row.runtime_fencing_token)>guard.fencingToken)throw new AgentJobLeaseLostError();return row.runtime_snapshot&&Object.keys(row.runtime_snapshot as object).length>0?row.runtime_snapshot:undefined;});}
  async saveRuntimeSnapshot(guard:AgentJobGuard,snapshot:unknown,state:string):Promise<void>{const encoded=JSON.stringify(snapshot);if(encoded.length>131_072||/(?:api[_-]?key|access[_-]?token|password|private[_-]?key)/i.test(encoded))throw new Error("RUNTIME_SNAPSHOT_REJECTED");await this.tx(async client=>{const claim=await this.loadOwned(client,guard,true);if(claim.cancelRequested&&!['CANCELLATION_REQUESTED','CANCELLED'].includes(state))throw new AgentJobCancellationRequestedError();const updated=await client.query("UPDATE builder.agent_runtime_runs SET runtime_snapshot=$3::jsonb,runtime_fencing_token=$4,state=$5 WHERE project_id=$1 AND run_id=$2 AND runtime_fencing_token<=$4",[claim.projectId,claim.task.runId,encoded,guard.fencingToken,state]);if(!updated.rowCount)throw new AgentJobLeaseLostError();});}
  private async finish(guard:AgentJobGuard,resultValue:AgentResult,messageId:string,event:"COMPLETED"|"CANCELLED",confirmationKind?:CancellationConfirmationKind){
    const result=parseAgentResult(resultValue);const requestedEvent=event;const semanticDigest=canonicalJsonDigest({event:requestedEvent,jobId:guard.jobId,result,confirmationKind:confirmationKind??null});
    return this.tx(async client=>{
      const prior=(await client.query<{semantic_digest:string|null}>("SELECT semantic_digest FROM builder.inbox_events WHERE consumer_identity='agent-job-completion' AND message_id=$1",[messageId])).rows[0];
      if(prior){if(prior.semantic_digest!==semanticDigest)throw new Error("COMPLETION_REPLAY_DIVERGED");return this.getStatusWith(client,guard.jobId);}
      const claim=await this.loadOwned(client,guard,true);const now=await this.databaseNow(client);
      if(result.runId!==claim.task.runId||result.projectId!==claim.projectId||result.taskId!==claim.task.taskId||result.attemptId!==claim.task.attemptId)throw new Error("RESULT_BINDING_MISMATCH");
      if(event==="CANCELLED"&&result.status!=="CANCELLED")throw new Error("CANCEL_RESULT_REQUIRED");
      if(event==="COMPLETED"&&result.status==="CANCELLED")throw new Error("COMPLETE_RESULT_INVALID");
      if(event==="CANCELLED"&&!claim.cancelRequested)throw new Error("CANCEL_NOT_REQUESTED");
      if(event==="CANCELLED"&&!confirmationKind)throw new Error("CANCEL_CONFIRMATION_REQUIRED");
      if(event==="CANCELLED"&&confirmationKind?.startsWith("RUNTIME_")&&claim.cancelAttemptCount<1)throw new Error("CANCEL_ATTEMPT_REQUIRED");
      await client.query("INSERT INTO builder.inbox_events(project_id,consumer_identity,message_id,status,semantic_digest) VALUES($1,'agent-job-completion',$2,'PROCESSING',$3)",[claim.projectId,messageId,semanticDigest]);
      let effectiveResult=result;
      if(claim.cancelRequested&&event==="COMPLETED"){
        confirmationKind="RUNTIME_TERMINAL_OBSERVED";
        effectiveResult=parseAgentResult({schemaVersion:1,projectId:claim.projectId,taskId:claim.task.taskId,attemptId:claim.task.attemptId,runId:claim.task.runId,status:"CANCELLED",findings:[],artifacts:[],decisions:[],errorCode:null});
        await this.audit(client,claim.projectId,guard.jobId,"LATE_COMPLETION_DISCARDED",guard.fencingToken,{resultStatus:result.status});event="CANCELLED";
      }
      if(event==="CANCELLED"){
        if(!confirmationKind)throw new Error("CANCEL_CONFIRMATION_REQUIRED");
        await client.query("UPDATE builder.background_jobs SET cancel_confirmed_at=$2::timestamptz,cancel_confirmation_kind=$3,cancel_last_outcome='CONFIRMED',cancel_last_error_code=NULL WHERE id=$1",[guard.jobId,now,confirmationKind]);
        await this.audit(client,claim.projectId,guard.jobId,"CANCEL_CONFIRMED",guard.fencingToken,{confirmationKind});
      }
      const inserted=await client.query<{id:string}>("INSERT INTO builder.agent_runtime_results(project_id,run_id,schema_version,status,result_payload) VALUES($1,$2,1,$3,$4::jsonb) RETURNING id",[claim.projectId,effectiveResult.runId,effectiveResult.status,JSON.stringify(effectiveResult)]);
      const resultId=inserted.rows[0]!.id;const runState=effectiveResult.status==="SUCCESS"?"SUCCEEDED":effectiveResult.status==="TIMEOUT"?"TIMED_OUT":effectiveResult.status==="SECURITY_BLOCK"||effectiveResult.status==="LEGAL_COUNSEL_REQUIRED"?"BLOCKED":effectiveResult.status==="CANCELLED"?"CANCELLED":"FAILED";const jobState=event==="CANCELLED"?"CANCELLED":effectiveResult.status==="SUCCESS"||effectiveResult.status==="SECURITY_BLOCK"||effectiveResult.status==="LEGAL_COUNSEL_REQUIRED"?"SUCCEEDED":"FAILED";
      await client.query("UPDATE builder.agent_runtime_runs SET state=$3,result_id=$4,terminal_at=$5 WHERE project_id=$1 AND run_id=$2",[claim.projectId,effectiveResult.runId,runState,resultId,now]);
      const updated=await client.query("UPDATE builder.background_jobs SET status=$5,agent_result_id=$6,terminal_at=$7,lease_expires_at=NULL WHERE id=$1 AND lease_owner=$2 AND claim_idempotency_key=$3 AND fencing_token=$4",[guard.jobId,guard.workerId,guard.claimId,guard.fencingToken,jobState,resultId,now]);if(!updated.rowCount)throw new AgentJobLeaseLostError();
      await this.audit(client,claim.projectId,guard.jobId,event,guard.fencingToken,{resultStatus:effectiveResult.status,resultId});await this.outbox(client,claim.projectId,guard.jobId,event==="CANCELLED"?"AGENT_JOB_CANCELLED":"AGENT_JOB_COMPLETED",`${guard.jobId}:${event.toLowerCase()}`);await client.query("UPDATE builder.inbox_events SET status='PROCESSED',processed_at=$2 WHERE consumer_identity='agent-job-completion' AND message_id=$1",[messageId,now]);return this.getStatusWith(client,guard.jobId);
    });
  }
  private async lockOwned(client:PoolClient,guard:AgentJobGuard,active:boolean):Promise<Date>{const found=await client.query("SELECT 1 FROM builder.background_jobs WHERE id=$1 AND lease_owner=$2 AND claim_idempotency_key=$3 AND fencing_token=$4 AND status IN ('CLAIMED','RUNNING','CANCELLING') FOR UPDATE",[guard.jobId,guard.workerId,guard.claimId,guard.fencingToken]);if(!found.rowCount)throw new AgentJobLeaseLostError();const sampled=await client.query<{now:Date;active:boolean}>("WITH authoritative AS MATERIALIZED (SELECT clock_timestamp() AS now) SELECT authoritative.now,job.lease_expires_at>authoritative.now AS active FROM builder.background_jobs job CROSS JOIN authoritative WHERE job.id=$1",[guard.jobId]);if(active&&sampled.rows[0]?.active!==true)throw new AgentJobLeaseLostError();return sampled.rows[0]!.now;}
  private async loadOwned(client:PoolClient,guard:AgentJobGuard,active:boolean){await this.lockOwned(client,guard,active);const result=await client.query<JobRow>(`SELECT job.id,job.project_id,job.status,job.retry_count,job.max_retries,job.lease_owner,job.claim_idempotency_key,job.fencing_token,job.lease_expires_at,job.cancel_requested_at,job.cancel_attempt_count,job.cancel_max_attempts,job.cancel_last_outcome,job.cancel_last_error_code,job.cancel_confirmed_at,job.cancel_confirmation_kind,job.agent_run_id,job.agent_attempt_id,result.result_payload,
    task.schema_version,task.task_id,task.attempt_id,task.run_id,task.role,task.scenario,task.input_ref,task.repair_ordinal FROM builder.background_jobs job JOIN builder.agent_runtime_tasks task ON task.project_id=job.project_id AND task.run_id=job.agent_run_id LEFT JOIN builder.agent_runtime_results result ON result.id=job.agent_result_id WHERE job.id=$1`,[guard.jobId]);return this.mapClaim(result.rows[0]!);}
  private mapClaim(row:JobRow):AgentJobClaim{return{jobId:row.id,projectId:row.project_id,task:parseAgentTask({schemaVersion:row.schema_version,projectId:row.project_id,taskId:row.task_id,attemptId:row.attempt_id,runId:row.run_id,role:row.role,scenario:row.scenario,inputRef:row.input_ref,repairOrdinal:row.repair_ordinal}),workerId:row.lease_owner!,claimId:row.claim_idempotency_key!,fencingToken:Number(row.fencing_token),leaseExpiresAt:row.lease_expires_at!,retryCount:row.retry_count,maxRetries:row.max_retries,cancelRequested:row.cancel_requested_at!==null,cancelAttemptCount:row.cancel_attempt_count,cancelMaxAttempts:row.cancel_max_attempts,cancelLastOutcome:row.cancel_last_outcome,cancelLastErrorCode:row.cancel_last_error_code,cancelConfirmedAt:row.cancel_confirmed_at,cancelConfirmationKind:row.cancel_confirmation_kind};}
  private async getStatusWith(client:Pick<Pool,"query">,jobId:string){const result=await client.query<JobRow>("SELECT job.id,job.project_id,job.status,job.retry_count,job.max_retries,job.fencing_token,job.cancel_requested_at,job.cancel_attempt_count,job.cancel_max_attempts,job.cancel_last_outcome,job.cancel_last_error_code,job.cancel_confirmed_at,job.cancel_confirmation_kind,job.agent_run_id,result.result_payload FROM builder.background_jobs job LEFT JOIN builder.agent_runtime_results result ON result.id=job.agent_result_id WHERE job.id=$1",[jobId]);const row=result.rows[0];if(!row)throw new Error("AGENT_JOB_NOT_FOUND");return{jobId:row.id,projectId:row.project_id,runId:row.agent_run_id,status:row.status,retryCount:row.retry_count,maxRetries:row.max_retries,fencingToken:row.fencing_token?Number(row.fencing_token):null,result:row.result_payload?parseAgentResult(row.result_payload):null,cancelRequested:row.cancel_requested_at!==null,cancelAttemptCount:row.cancel_attempt_count,cancelMaxAttempts:row.cancel_max_attempts,cancelLastOutcome:row.cancel_last_outcome,cancelLastErrorCode:row.cancel_last_error_code,cancelConfirmedAt:row.cancel_confirmed_at,cancelConfirmationKind:row.cancel_confirmation_kind};}
  private async audit(client:PoolClient,projectId:string,jobId:string,eventType:string,fencingToken:number|null,metadata:Record<string,unknown>){await client.query("INSERT INTO builder.agent_job_audit_events(project_id,job_id,event_type,fencing_token,metadata) VALUES($1,$2,$3,$4,$5::jsonb)",[projectId,jobId,eventType,fencingToken,JSON.stringify(metadata)]);}
  private async outbox(client:PoolClient,projectId:string,jobId:string,eventType:string,key:string){await client.query("INSERT INTO builder.outbox_events(project_id,event_type,aggregate_type,aggregate_id,schema_version,policy_version,idempotency_key,status) VALUES($1,$2,'AGENT_JOB',$3,1,'worker-fake-runtime-1',$4,'PENDING') ON CONFLICT(project_id,idempotency_key) DO NOTHING",[projectId,eventType,jobId,key]);}
  private async databaseNow(client:PoolClient):Promise<Date>{return(await client.query<{now:Date}>("SELECT clock_timestamp() now")).rows[0]!.now;}
  private async tx<T>(operation:(client:PoolClient)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query("BEGIN");const result=await operation(client);await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  private assertOwner(workerId:string,claimId:string,leaseMs:number){if(!/^[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}$/.test(workerId)||!/^[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}$/.test(claimId)||!Number.isSafeInteger(leaseMs)||leaseMs<1||leaseMs>120_000)throw new Error("INVALID_CLAIM");}
  private assertEnqueue(input:EnqueueAgentJob){if(input.requestDigest!==canonicalAgentOperationDigest("enqueue",input.task)||!Number.isSafeInteger(input.maxRetries)||input.maxRetries<0||input.maxRetries>20)throw new Error("INVALID_ENQUEUE");for(const value of [input.messageId,input.traceId])if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))throw new Error("INVALID_UUID");}
}

function canonicalJsonDigest(value:unknown):string{const canonical=(item:unknown):unknown=>Array.isArray(item)?item.map(canonical):item&&typeof item==="object"?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b)).map(([key,entry])=>[key,canonical(entry)])):item;return createHash("sha256").update(JSON.stringify(canonical(value))).digest("hex");}
