import { randomUUID } from "node:crypto";
import { Pool } from "pg";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import type { ProjectId } from "@software-builder/core";
import { AgentRegistryService,DEVELOPMENT_AGENT_SEEDS,HmacCapabilityAuthority,PostgresDatabase,PostgresProjectContextIssuer,seedDevelopmentAgentRegistry,type AgentDefinitionVersion } from "./index.js";
import { migrate,resetDatabase } from "./migrations.js";

const adminUrl=process.env.TEST_DATABASE_URL;
const waitForDatabaseQuiescence=async(pool:Pool,timeoutMs=5_000)=>{const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){const active=await pool.query<{count:string}>("SELECT count(*) count FROM pg_stat_activity WHERE datname=current_database() AND pid<>pg_backend_pid()");if(Number(active.rows[0]!.count)===0)return;await new Promise(resolve=>setTimeout(resolve,5));}throw new Error("Timed out waiting for test database quiescence");};

describe("Agent Registry PostgreSQL integration",()=>{
  let admin:Pool;let db:PostgresDatabase;let authority:HmacCapabilityAuthority;let runtimeUrl:string;let contextUrl:string;let capability:ReturnType<HmacCapabilityAuthority["issueProject"]>;let service:AgentRegistryService;
  beforeAll(async()=>{
    if(!adminUrl)throw new Error("TEST_DATABASE_URL ist fuer Agent-Registry-Integration verpflichtend; Skips sind nicht zulaessig.");
    const parsed=new URL(adminUrl);if(!parsed.pathname.toLowerCase().endsWith("_test"))throw new Error("TEST_DATABASE_URL muss auf _test enden.");
    admin=new Pool({connectionString:adminUrl});await waitForDatabaseQuiescence(admin);await resetDatabase(admin,{connectionString:adminUrl,environment:"test"});expect(await migrate(admin)).toEqual([]);
    await admin.query("SELECT builder.provision_runtime_password('registry-integration-only-123')");await admin.query("SELECT builder.provision_context_password('registry-context-integration-only-123')");
    parsed.username="builder_app_login";parsed.password="registry-integration-only-123";runtimeUrl=parsed.toString();const context=new URL(parsed);context.username="builder_context_login";context.password="registry-context-integration-only-123";contextUrl=context.toString();
    authority=new HmacCapabilityAuthority();const issuer=await PostgresProjectContextIssuer.connect(contextUrl);db=await PostgresDatabase.connectRuntime(runtimeUrl,issuer,authority,authority);
    const projectId=randomUUID() as ProjectId;await db.projects.create(authority.issueBootstrap("registry-test","INTEGRATION_TEST"),{id:projectId,status:"PLANNING"},{actorScope:"INTEGRATION_TEST",actorIdentityId:"registry-test",idempotencyKey:`project-${projectId}`,requestDigest:"a".repeat(64),aggregateType:"PROJECT",aggregateId:projectId,transition:"CREATE",newState:"PLANNING",reasonCode:"SYNTHETIC_TEST",policyVersion:"test-1",eventType:"PROJECT_CREATED",schemaVersion:1});
    capability=authority.issueProject(projectId,{subject:"registry-test",actorScope:"INTEGRATION_TEST",allowedRoles:["INTEGRATION_TEST"],allowedOperations:["agent_registry:read","agent_registry:append"]},120_000);service=new AgentRegistryService(db.agentRegistry);
  },30_000);
  afterAll(async()=>{await db?.close();if(admin){await admin.end();const cleanup=new Pool({connectionString:adminUrl!});try{await waitForDatabaseQuiescence(cleanup);await resetDatabase(cleanup,{connectionString:adminUrl!,environment:"test"});}finally{await cleanup.end();}}},30_000);

  const create=async(agentKey:string,version=1,agentId?:string)=>service.createDefinition(capability,{agentKey,...(agentId===undefined?{}:{agentId}),displayName:agentKey,role:"PLANNER",description:"Synthetic integration definition.",version,instructions:"Plan only the scoped synthetic development task.",allowedCapabilities:["documentation.read"],forbiddenCapabilities:["production.deploy"],modelConfiguration:{model:"development-model",reasoningLevel:"LOW",timeoutMs:1000,maxAttempts:1},createdBy:"synthetic-integration-test"});
  const insertRawVersion=(agentId:string,agentKey:string,version:number)=>admin.query("INSERT INTO builder.agent_registry_versions(agent_id,agent_key,display_name,role,description,version,revision,status,instructions,created_by) VALUES($1,$2,'Raw synthetic','PLANNER','Synthetic raw registry definition.',$3,$3,'DRAFT','Plan only the scoped raw database test.','synthetic-integration-test')",[agentId,agentKey,version]);

  it("persistiert alle acht Development-Seeds und listet sie nach Rolle oder Status",async()=>{await seedDevelopmentAgentRegistry(service,capability);expect(await service.list(capability,{status:"DRAFT"})).toHaveLength(8);expect((await service.list(capability,{role:"LEGAL_DE_EU"})).map(item=>item.agentKey)).toEqual(["legal-de-eu"]);expect(DEVELOPMENT_AGENT_SEEDS).toHaveLength(8);});
  it("weist denselben agentKey mit anderer agentId und dieselbe agentId mit anderem agentKey eindeutig ab",async()=>{const agentId=randomUUID();const stored=await create("bijective-agent",1,agentId);expect(stored.agentId).toBe(agentId);await expect(create(stored.agentKey,1,randomUUID())).rejects.toThrow("AGENT_IDENTITY_KEY_CONFLICT");await expect(create("bijective-agent-other",1,agentId)).rejects.toThrow("AGENT_IDENTITY_ID_CONFLICT");const identities=(await admin.query<{key_count:number;id_count:number}>("SELECT (SELECT count(*)::int FROM builder.agent_registry_identities WHERE agent_key=$1) key_count,(SELECT count(*)::int FROM builder.agent_registry_identities WHERE agent_id=$2) id_count",[stored.agentKey,agentId])).rows[0];expect(identities).toEqual({key_count:1,id_count:1});});
  it("verwendet fuer alle Versionen nur die kanonische agentId und lehnt caller-seitige Abweichungen ab",async()=>{const first=await create("canonical-version-agent",1,randomUUID());const second=await service.createVersion(capability,{agentKey:first.agentKey,agentId:first.agentId,displayName:"Canonical version two",role:"PLANNER",description:"Synthetic canonical second version.",version:2,instructions:"Plan the canonical second synthetic definition.",allowedCapabilities:["documentation.read"],forbiddenCapabilities:["production.deploy"],createdBy:"synthetic-integration-test"});const third=await service.createVersion(capability,{agentKey:first.agentKey,displayName:"Canonical version three",role:"PLANNER",description:"Synthetic canonical third version.",version:3,instructions:"Plan the canonical third synthetic definition.",allowedCapabilities:["documentation.read"],forbiddenCapabilities:["production.deploy"],createdBy:"synthetic-integration-test"});expect([second.agentId,third.agentId]).toEqual([first.agentId,first.agentId]);await expect(service.createVersion(capability,{agentKey:first.agentKey,agentId:randomUUID(),displayName:"Rejected identity",role:"PLANNER",description:"Synthetic rejected identity version.",version:4,instructions:"Reject an identity mismatch before appending a version.",allowedCapabilities:["documentation.read"],forbiddenCapabilities:["production.deploy"],createdBy:"synthetic-integration-test"})).rejects.toThrow("AGENT_IDENTITY_MISMATCH");const persisted=(await admin.query<{versions:number;agent_ids:number}>("SELECT count(*)::int versions,count(DISTINCT agent_id)::int agent_ids FROM builder.agent_registry_versions WHERE agent_key=$1",[first.agentKey])).rows[0];expect(persisted).toEqual({versions:3,agent_ids:1});});
  it("linearisiert parallele createDefinition-Aufrufe fuer denselben agentKey auf genau eine Identitaet",async()=>{const agentKey="parallel-definition-agent";const candidateIds=[randomUUID(),randomUUID()] as const;const results=await Promise.allSettled([create(agentKey,1,candidateIds[0]),create(agentKey,1,candidateIds[1])]);const fulfilled=results.filter((result):result is PromiseFulfilledResult<AgentDefinitionVersion>=>result.status==="fulfilled");const rejected=results.filter((result):result is PromiseRejectedResult=>result.status==="rejected");expect(fulfilled).toHaveLength(1);expect(rejected).toHaveLength(1);expect(String(rejected[0]!.reason)).toMatch(/AGENT_IDENTITY_KEY_CONFLICT/);expect(candidateIds).toContain(fulfilled[0]!.value.agentId);const persisted=(await admin.query<{identities:number;versions:number;agent_ids:number}>("SELECT (SELECT count(*)::int FROM builder.agent_registry_identities WHERE agent_key=$1) identities,(SELECT count(*)::int FROM builder.agent_registry_versions WHERE agent_key=$1) versions,(SELECT count(DISTINCT agent_id)::int FROM builder.agent_registry_versions WHERE agent_key=$1) agent_ids",[agentKey])).rows[0];expect(persisted).toEqual({identities:1,versions:1,agent_ids:1});});
  it("verhindert parallele Identitaeten mit derselben agentId und unterschiedlichen agentKeys",async()=>{const agentId=randomUUID();const keys=["parallel-id-agent-a","parallel-id-agent-b"] as const;const results=await Promise.allSettled([create(keys[0],1,agentId),create(keys[1],1,agentId)]);const fulfilled=results.filter((result):result is PromiseFulfilledResult<AgentDefinitionVersion>=>result.status==="fulfilled");const rejected=results.filter((result):result is PromiseRejectedResult=>result.status==="rejected");expect(fulfilled).toHaveLength(1);expect(rejected).toHaveLength(1);expect(String(rejected[0]!.reason)).toMatch(/AGENT_IDENTITY_ID_CONFLICT/);expect(keys).toContain(fulfilled[0]!.value.agentKey);const persisted=(await admin.query<{identities:number;versions:number;agent_keys:number}>("SELECT (SELECT count(*)::int FROM builder.agent_registry_identities WHERE agent_id=$1) identities,(SELECT count(*)::int FROM builder.agent_registry_versions WHERE agent_id=$1) versions,(SELECT count(DISTINCT agent_key)::int FROM builder.agent_registry_versions WHERE agent_id=$1) agent_keys",[agentId])).rows[0];expect(persisted).toEqual({identities:1,versions:1,agent_keys:1});});
  it("erstellt und liest unveraenderliche Versionen mit stabiler agentId",async()=>{const first=await create("versioned-agent");const second=await service.createVersion(capability,{agentKey:first.agentKey,displayName:"Version two",role:"PLANNER",description:"Synthetic second version.",version:2,instructions:"Plan the second synthetic definition.",allowedCapabilities:["documentation.read"],forbiddenCapabilities:["production.deploy"],createdBy:"synthetic-integration-test"});expect(second.agentId).toBe(first.agentId);expect((await service.getVersion(capability,first.agentKey,1))?.instructions).toBe(first.instructions);await expect(admin.query("UPDATE builder.agent_registry_versions SET instructions='mutated' WHERE id=$1",[first.id])).rejects.toThrow(/immutable/);});
  it("laesst bei paralleler Erstellung derselben Version genau einen Erfolg zu",async()=>{const first=await create("duplicate-agent");const input={agentKey:first.agentKey,displayName:"Duplicate candidate",role:"PLANNER" as const,description:"Synthetic duplicate candidate.",version:2,instructions:"Plan the duplicate version test.",allowedCapabilities:["documentation.read"],forbiddenCapabilities:["production.deploy"],createdBy:"synthetic-integration-test"};const results=await Promise.allSettled([service.createVersion(capability,input),service.createVersion(capability,input)]);expect(results.filter(result=>result.status==="fulfilled")).toHaveLength(1);expect(results.filter(result=>result.status==="rejected")).toHaveLength(1);expect(await service.getVersion(capability,first.agentKey,2)).toBeDefined();});
  it("linearisiert parallele Aktivierungen auf genau eine ACTIVE-Version",async()=>{const first=await create("activation-agent");for(const version of [2,3])await service.createVersion(capability,{agentKey:first.agentKey,displayName:`Version ${version}`,role:"PLANNER",description:"Synthetic activation candidate.",version,instructions:`Plan synthetic version ${version}.`,allowedCapabilities:["documentation.read"],forbiddenCapabilities:["production.deploy"],createdBy:"synthetic-integration-test"});const results=await Promise.allSettled([service.activate(capability,first.agentKey,2),service.activate(capability,first.agentKey,3)]);expect(results.every(result=>result.status==="fulfilled")).toBe(true);const active=await service.list(capability,{status:"ACTIVE"});expect(active.filter(item=>item.agentKey===first.agentKey)).toHaveLength(1);expect([2,3]).toContain((await service.getActive(capability,first.agentKey))?.version);});
  it("rollt eine fehlgeschlagene Aktivierung ohne Teilzustand zurueck und reaktiviert RETIRED nie",async()=>{const first=await create("rollback-agent");await service.activate(capability,first.agentKey,1);await expect(service.activate(capability,first.agentKey,999)).rejects.toThrow(/unbekannt/);expect((await service.getActive(capability,first.agentKey))?.version).toBe(1);await service.retireActive(capability,first.agentKey);await expect(service.activate(capability,first.agentKey,1)).rejects.toThrow(/RETIRED/);expect(await service.getActive(capability,first.agentKey)).toBeUndefined();});
  it("liest die kanonische Identitaet nach Repository-Neuinstanziierung und verwendet sie fuer neue Versionen",async()=>{const stored=await create("restart-agent");const issuer=await PostgresProjectContextIssuer.connect(contextUrl);const restarted=await PostgresDatabase.connectRuntime(runtimeUrl,issuer,authority,authority);try{const restartedService=new AgentRegistryService(restarted.agentRegistry);expect((await restartedService.getVersion(capability,stored.agentKey,stored.version))?.id).toBe(stored.id);const appended=await restartedService.createVersion(capability,{agentKey:stored.agentKey,displayName:"Restart version two",role:"PLANNER",description:"Synthetic persisted identity after restart.",version:2,instructions:"Reuse the persisted canonical identity after restart.",allowedCapabilities:["documentation.read"],forbiddenCapabilities:["production.deploy"],createdBy:"synthetic-integration-test"});expect(appended.agentId).toBe(stored.agentId);}finally{await restarted.close();}const persisted=(await admin.query<{identities:number;versions:number;agent_ids:number}>("SELECT (SELECT count(*)::int FROM builder.agent_registry_identities WHERE agent_key=$1) identities,(SELECT count(*)::int FROM builder.agent_registry_versions WHERE agent_key=$1) versions,(SELECT count(DISTINCT agent_id)::int FROM builder.agent_registry_versions WHERE agent_key=$1) agent_ids",[stored.agentKey])).rows[0];expect(persisted).toEqual({identities:1,versions:2,agent_ids:1});});
  it("rollt Identity und Version bei einem deterministischen AFTER-INSERT-Fehler vollstaendig zurueck",async()=>{const agentKey="post-mutation-rollback-agent";const agentId=randomUUID();await admin.query("CREATE FUNCTION builder.test_fail_agent_registry_version_insert() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'SYNTHETIC_AGENT_REGISTRY_POST_MUTATION_FAILURE'; END $$");try{await admin.query("CREATE TRIGGER test_fail_agent_registry_version_insert AFTER INSERT ON builder.agent_registry_versions FOR EACH ROW WHEN (NEW.agent_key='post-mutation-rollback-agent') EXECUTE FUNCTION builder.test_fail_agent_registry_version_insert()");await expect(create(agentKey,1,agentId)).rejects.toThrow("SYNTHETIC_AGENT_REGISTRY_POST_MUTATION_FAILURE");const persisted=(await admin.query<{identities:number;versions:number}>("SELECT (SELECT count(*)::int FROM builder.agent_registry_identities WHERE agent_key=$1 OR agent_id=$2) identities,(SELECT count(*)::int FROM builder.agent_registry_versions WHERE agent_key=$1 OR agent_id=$2) versions",[agentKey,agentId])).rows[0];expect(persisted).toEqual({identities:0,versions:0});}finally{try{await admin.query("DROP TRIGGER IF EXISTS test_fail_agent_registry_version_insert ON builder.agent_registry_versions");}finally{await admin.query("DROP FUNCTION IF EXISTS builder.test_fail_agent_registry_version_insert()");}}});
  it("erzwingt Status-, Rollen-, Identitaets- und Secret-Constraints auch in PostgreSQL",async()=>{const invalidRoleId=randomUUID();await admin.query("INSERT INTO builder.agent_registry_identities(agent_key,agent_id,created_by) VALUES('invalid-db',$1,'synthetic-test')",[invalidRoleId]);await expect(admin.query("INSERT INTO builder.agent_registry_versions(agent_id,agent_key,display_name,role,description,version,revision,status,instructions,created_by) VALUES($1,'invalid-db','Invalid','UNKNOWN','Synthetic',1,1,'DRAFT','Synthetic instructions','synthetic-test')",[invalidRoleId])).rejects.toThrow();const secretId=randomUUID();await admin.query("INSERT INTO builder.agent_registry_identities(agent_key,agent_id,created_by) VALUES('secret-db',$1,'synthetic-test')",[secretId]);await expect(admin.query("INSERT INTO builder.agent_registry_versions(agent_id,agent_key,display_name,role,description,version,revision,status,instructions,model_config,created_by) VALUES($1,'secret-db','Invalid','PLANNER','Synthetic',1,1,'DRAFT','api_key=not-allowed',$2::jsonb,'synthetic-test')",[secretId,JSON.stringify({apiKey:"placeholder"})])).rejects.toThrow();const bound=await create("database-bound-agent");await expect(insertRawVersion(randomUUID(),bound.agentKey,2)).rejects.toMatchObject({constraint:"agent_registry_versions_identity_fk"});await expect(insertRawVersion(bound.agentId,"database-bound-agent-other",2)).rejects.toMatchObject({constraint:"agent_registry_versions_identity_fk"});});
});
