import { createHash,randomUUID } from "node:crypto";
import { Pool } from "pg";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import type { ProjectId } from "@software-builder/core";
import { canonicalAgentOperationDigest,FakeAgentRuntime,type AgentTask } from "@software-builder/agent-runtime";
import { AgentAssignmentService,AgentJobRepository,AgentRegistryService,HmacCapabilityAuthority,PostgresDatabase,PostgresProjectContextIssuer,createAgentJobCompletionContext,type AgentDefinitionVersion,type AgentRole,type AssignActiveAgentInput } from "./index.js";
import { RegisteredWorkerProcessFixtureForTest } from "./agent-job-test-fixture.js";
import { migrate,resetDatabase } from "./migrations.js";

const adminUrl=process.env.TEST_DATABASE_URL;
const digest=(value:string)=>createHash("sha256").update(value).digest("hex");
const testWorkers=new RegisteredWorkerProcessFixtureForTest("agent-assignment-integration");
const waitForDatabaseQuiescence=async(pool:Pool,timeoutMs=5_000)=>{const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){const active=await pool.query<{count:string}>("SELECT count(*) count FROM pg_stat_activity WHERE datname=current_database() AND pid<>pg_backend_pid()");if(Number(active.rows[0]!.count)===0)return;await new Promise(resolve=>setTimeout(resolve,5));}throw new Error("Timed out waiting for test database quiescence");};

describe("Agent Assignment PostgreSQL integration",()=>{
  let admin:Pool;let db:PostgresDatabase;let authority:HmacCapabilityAuthority;let runtimeUrl:string;let contextUrl:string;let projectId:ProjectId;let assignments:AgentAssignmentService;let registry:AgentRegistryService;let planner:AgentDefinitionVersion;
  const assignmentCapability=()=>authority.issueProject(projectId,{subject:"assignment-test",actorScope:"INTEGRATION_TEST",allowedRoles:["INTEGRATION_TEST"],allowedOperations:["agent_assignment:read","agent_assignment:append"]},60_000);
  const registryCapability=()=>authority.issueProject(projectId,{subject:"assignment-test",actorScope:"INTEGRATION_TEST",allowedRoles:["INTEGRATION_TEST"],allowedOperations:["agent_registry:read","agent_registry:append"]},60_000);
  const createAgent=async(agentKey:string,role:AgentRole,version=1)=>registry.createDefinition(registryCapability(),{agentKey,displayName:`Synthetic ${agentKey}`,role,description:"Synthetic assignment integration definition.",version,instructions:"Perform only the scoped synthetic development assignment test.",allowedCapabilities:["assignment.test"],forbiddenCapabilities:["production.deploy"],createdBy:"synthetic-assignment-test"});
  const createVersion=async(agent:AgentDefinitionVersion,version:number)=>registry.createVersion(registryCapability(),{agentKey:agent.agentKey,displayName:`Synthetic ${agent.agentKey} v${version}`,role:agent.role,description:"Synthetic assignment integration version.",version,instructions:`Perform only synthetic assignment test version ${version}.`,allowedCapabilities:["assignment.test"],forbiddenCapabilities:["production.deploy"],createdBy:"synthetic-assignment-test"});
  const createJob=async()=>{const jobId=randomUUID();await admin.query("INSERT INTO builder.background_jobs(id,project_id,job_type,aggregate_type,aggregate_id,schema_version,policy_version,idempotency_key,expected_aggregate_version,trace_id,status,max_retries) VALUES($1,$2,'ASSIGNMENT_TEST','WORKFLOW',$2,1,'assignment-test-1',$3,1,$4,'PENDING',0)",[jobId,projectId,digest(`assignment-job:${jobId}`),randomUUID()]);return jobId;};
  const input=(jobId:string,overrides:Partial<AssignActiveAgentInput>={}):AssignActiveAgentInput=>({assignmentId:randomUUID(),projectId,jobId,requiredRole:"PLANNER",createdBy:"synthetic-assignment-test",...overrides});

  beforeAll(async()=>{
    if(!adminUrl)throw new Error("TEST_DATABASE_URL ist fuer Agent-Assignment-Integration verpflichtend; Skips sind nicht zulaessig.");
    const parsed=new URL(adminUrl);if(!parsed.pathname.toLowerCase().endsWith("_test"))throw new Error("TEST_DATABASE_URL muss auf _test enden.");
    admin=new Pool({connectionString:adminUrl});expect(Number((await admin.query<{server_version_num:string}>("SHOW server_version_num")).rows[0]!.server_version_num)).toBeGreaterThanOrEqual(180000);await waitForDatabaseQuiescence(admin);await resetDatabase(admin,{connectionString:adminUrl,environment:"test"});expect(await migrate(admin)).toEqual([]);
    await admin.query("SELECT builder.provision_runtime_password('assignment-integration-only-123')");await admin.query("SELECT builder.provision_context_password('assignment-context-integration-only-123')");
    parsed.username="builder_app_login";parsed.password="assignment-integration-only-123";runtimeUrl=parsed.toString();const context=new URL(parsed);context.username="builder_context_login";context.password="assignment-context-integration-only-123";contextUrl=context.toString();
    authority=new HmacCapabilityAuthority();db=await PostgresDatabase.connectRuntime(runtimeUrl,await PostgresProjectContextIssuer.connect(contextUrl),authority,authority);projectId=randomUUID() as ProjectId;
    await db.projects.create(authority.issueBootstrap("assignment-test","INTEGRATION_TEST"),{id:projectId,status:"PLANNING"},{actorScope:"INTEGRATION_TEST",actorIdentityId:"assignment-test",idempotencyKey:`project-${projectId}`,requestDigest:digest(`project-${projectId}`),aggregateType:"PROJECT",aggregateId:projectId,transition:"CREATE",newState:"PLANNING",reasonCode:"SYNTHETIC_TEST",policyVersion:"test-1",eventType:"PROJECT_CREATED",schemaVersion:1});
    assignments=new AgentAssignmentService(db.agentAssignments);registry=new AgentRegistryService(db.agentRegistry);planner=await createAgent("assignment-planner","PLANNER");planner=await registry.activate(registryCapability(),planner.agentKey,planner.version);
  },30_000);

  afterAll(async()=>{await db?.close();if(admin){await admin.end();const cleanup=new Pool({connectionString:adminUrl!});try{await waitForDatabaseQuiescence(cleanup);await resetDatabase(cleanup,{connectionString:adminUrl!,environment:"test"});}finally{await cleanup.end();}}},30_000);

  it("bindet einen Job an die konkrete ACTIVE Registry-Version und liest nach Job und Projekt",async()=>{const jobId=await createJob();const assigned=await assignments.assignActiveAgent(assignmentCapability(),input(jobId));expect(assigned).toMatchObject({projectId,jobId,requiredRole:"PLANNER",agentId:planner.agentId,agentKey:planner.agentKey,agentVersion:1,assignmentStatus:"ASSIGNED",createdBy:"synthetic-assignment-test"});expect(await assignments.getAssignmentByJob(assignmentCapability(),jobId)).toEqual(assigned);expect(await assignments.listAssignmentsByProject(assignmentCapability())).toContainEqual(assigned);});

  it("behandelt null und mehrere ACTIVE Kandidaten pro Rolle fail-closed",async()=>{await expect(assignments.assignActiveAgent(assignmentCapability(),input(await createJob(),{requiredRole:"ARCHITECT"}))).rejects.toThrow("AGENT_ASSIGNMENT_NO_ACTIVE_AGENT");const other=await createAgent("assignment-planner-other","PLANNER");await registry.activate(registryCapability(),other.agentKey,other.version);try{await expect(assignments.assignActiveAgent(assignmentCapability(),input(await createJob()))).rejects.toThrow("AGENT_ASSIGNMENT_AMBIGUOUS_ACTIVE_AGENT");}finally{await registry.retireActive(registryCapability(),other.agentKey);}});

  it("macht identische Wiederholungen seriell und parallel idempotent",async()=>{const sequential=input(await createJob());const first=await assignments.assignActiveAgent(assignmentCapability(),sequential);expect(await assignments.assignActiveAgent(assignmentCapability(),sequential)).toEqual(first);const parallel=input(await createJob());const results=await Promise.all([assignments.assignActiveAgent(assignmentCapability(),parallel),assignments.assignActiveAgent(assignmentCapability(),parallel)]);expect(results).toEqual([results[0],results[0]]);expect((await admin.query("SELECT 1 FROM builder.agent_assignments WHERE job_id=$1",[parallel.jobId])).rowCount).toBe(1);});

  it("laesst bei parallelen widerspruechlichen Zuweisungen hoechstens eine erfolgreich sein",async()=>{const jobId=await createJob();const results=await Promise.allSettled([assignments.assignActiveAgent(assignmentCapability(),input(jobId)),assignments.assignActiveAgent(assignmentCapability(),input(jobId))]);expect(results.filter(result=>result.status==="fulfilled")).toHaveLength(1);const rejected=results.find((result):result is PromiseRejectedResult=>result.status==="rejected");expect(String(rejected?.reason)).toContain("AGENT_ASSIGNMENT_CONFLICT");expect((await admin.query("SELECT 1 FROM builder.agent_assignments WHERE job_id=$1",[jobId])).rowCount).toBe(1);});

  it("lehnt widerspruechliche Assignment-ID, Rolle und Erstellerbindung vor Registry-Neuaufloesung ab",async()=>{const original=input(await createJob());const assigned=await assignments.assignActiveAgent(assignmentCapability(),original);await expect(assignments.assignActiveAgent(assignmentCapability(),{...original,assignmentId:randomUUID()})).rejects.toThrow("AGENT_ASSIGNMENT_CONFLICT");await expect(assignments.assignActiveAgent(assignmentCapability(),{...original,requiredRole:"ARCHITECT"})).rejects.toThrow("AGENT_ASSIGNMENT_CONFLICT");await expect(assignments.assignActiveAgent(assignmentCapability(),{...original,createdBy:"different-synthetic-actor"})).rejects.toThrow("AGENT_ASSIGNMENT_CONFLICT");expect(await assignments.getAssignmentByJob(assignmentCapability(),original.jobId)).toEqual(assigned);});

  it("bewahrt die gebundene Version waehrend Aktivierung und Retire unveraendert",async()=>{const original=input(await createJob());const assigned=await assignments.assignActiveAgent(assignmentCapability(),original);const version2=await createVersion(planner,2);planner=await registry.activate(registryCapability(),planner.agentKey,version2.version);const persisted=await assignments.getAssignmentByJob(assignmentCapability(),original.jobId);expect(persisted).toEqual(assigned);expect(persisted).toMatchObject({agentId:assigned.agentId,agentKey:assigned.agentKey,agentVersion:1});expect((await registry.getVersion(registryCapability(),assigned.agentKey,assigned.agentVersion))?.status).toBe("RETIRED");});

  it("linearisiert Registry-Aktivierung und Zuweisung auf einen konsistenten ACTIVE-at-insert Stand",async()=>{const version3=await createVersion(planner,3);const request=input(await createJob());const [activated,assigned]=await Promise.all([registry.activate(registryCapability(),planner.agentKey,version3.version),assignments.assignActiveAgent(assignmentCapability(),request)]);planner=activated;expect([2,3]).toContain(assigned.agentVersion);const history=await registry.getVersion(registryCapability(),assigned.agentKey,assigned.agentVersion);expect(history).toBeDefined();expect(assigned.agentId).toBe(planner.agentId);expect(await assignments.getAssignmentByJob(assignmentCapability(),request.jobId)).toEqual(assigned);});

  it("persistiert Zuweisungen ueber Repository-Neustart",async()=>{const request=input(await createJob());const assigned=await assignments.assignActiveAgent(assignmentCapability(),request);const restarted=await PostgresDatabase.connectRuntime(runtimeUrl,await PostgresProjectContextIssuer.connect(contextUrl),authority,authority);try{const service=new AgentAssignmentService(restarted.agentAssignments);expect(await service.getAssignmentByJob(assignmentCapability(),request.jobId)).toEqual(assigned);}finally{await restarted.close();}});

  it("rollt einen Datenbankfehler nach der Mutation vollstaendig zurueck",async()=>{const request=input(await createJob());await admin.query("CREATE FUNCTION builder.test_fail_agent_assignment_insert() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'SYNTHETIC_AGENT_ASSIGNMENT_POST_MUTATION_FAILURE'; END $$");try{await admin.query("CREATE TRIGGER test_fail_agent_assignment_insert AFTER INSERT ON builder.agent_assignments FOR EACH ROW EXECUTE FUNCTION builder.test_fail_agent_assignment_insert()");await expect(assignments.assignActiveAgent(assignmentCapability(),request)).rejects.toThrow("SYNTHETIC_AGENT_ASSIGNMENT_POST_MUTATION_FAILURE");expect((await admin.query("SELECT 1 FROM builder.agent_assignments WHERE assignment_id=$1 OR job_id=$2",[request.assignmentId,request.jobId])).rowCount).toBe(0);}finally{try{await admin.query("DROP TRIGGER IF EXISTS test_fail_agent_assignment_insert ON builder.agent_assignments");}finally{await admin.query("DROP FUNCTION IF EXISTS builder.test_fail_agent_assignment_insert() ");}}});

  it("macht RELEASED terminal und schuetzt die historische Bindung auch direkt in PostgreSQL",async()=>{const request=input(await createJob());const assigned=await assignments.assignActiveAgent(assignmentCapability(),request);const release={assignmentId:assigned.assignmentId,projectId,jobId:assigned.jobId,releasedBy:"synthetic-assignment-releaser"};const released=await assignments.releaseAssignment(assignmentCapability(),release);expect(released).toMatchObject({assignmentStatus:"RELEASED",releasedBy:release.releasedBy});expect(await assignments.releaseAssignment(assignmentCapability(),release)).toEqual(released);await expect(assignments.releaseAssignment(assignmentCapability(),{...release,releasedBy:"different-releaser"})).rejects.toThrow("AGENT_ASSIGNMENT_RELEASE_CONFLICT");await expect(assignments.assignActiveAgent(assignmentCapability(),request)).rejects.toThrow("AGENT_ASSIGNMENT_RELEASED");await expect(admin.query("UPDATE builder.agent_assignments SET agent_version=agent_version+1 WHERE assignment_id=$1",[assigned.assignmentId])).rejects.toThrow(/immutable/);await expect(admin.query("DELETE FROM builder.agent_assignments WHERE assignment_id=$1",[assigned.assignmentId])).rejects.toThrow(/cannot be deleted/);expect(await assignments.getAssignmentByJob(assignmentCapability(),assigned.jobId)).toEqual(released);});

  it("erzwingt ACTIVE Registry-Tupel und Rollenbindung auch bei direktem SQL",async()=>{const jobId=await createJob();await expect(admin.query("INSERT INTO builder.agent_assignments(assignment_id,project_id,job_id,required_role,agent_id,agent_key,agent_version,created_by) VALUES($1,$2,$3,'PLANNER',$4,$5,$6,'synthetic-direct-test')",[randomUUID(),projectId,jobId,planner.agentId,planner.agentKey,planner.version-1])).rejects.toThrow(/active registry candidate/);expect((await admin.query("SELECT 1 FROM builder.agent_assignments WHERE job_id=$1",[jobId])).rowCount).toBe(0);});

  it("liefert dem Fake-Claim die konkrete LEGAL-DE-EU-Bindung, lehnt Cross-Assignment atomar ab und auditiert terminal",async()=>{
    const jobs=new AgentJobRepository(admin);const task:AgentTask={schemaVersion:1,projectId,taskId:randomUUID(),attemptId:randomUUID(),runId:randomUUID(),role:"LEGAL",scenario:"SUCCESS",inputRef:"synthetic/assignment-input",repairOrdinal:0};const enqueued=await jobs.enqueue({task,messageId:randomUUID(),consumerIdentity:"assignment-fake-test",idempotencyKey:`assignment-fake-${task.runId}`,requestDigest:canonicalAgentOperationDigest("enqueue",task),traceId:randomUUID(),maxRetries:0});await expect(assignments.assignActiveAgent(assignmentCapability(),input(enqueued.jobId))).rejects.toThrow("AGENT_ASSIGNMENT_ROLE_MISMATCH");const legal=await createAgent("assignment-legal-de-eu","LEGAL_DE_EU");const activeLegal=await registry.activate(registryCapability(),legal.agentKey,legal.version);const request=input(enqueued.jobId,{requiredRole:"LEGAL_DE_EU"});const assigned=await assignments.assignActiveAgent(assignmentCapability(),request);const claim=await testWorkers.claimNext(jobs,"assignment-fake-worker","assignment-fake-claim",120_000);expect(claim).toMatchObject({jobId:enqueued.jobId,assignment:{assignmentId:assigned.assignmentId,agentId:activeLegal.agentId,agentKey:activeLegal.agentKey,agentVersion:activeLegal.version}});const result=(await new FakeAgentRuntime({now:()=>new Date("2026-01-01T00:00:00Z")}).startRun({runId:task.runId,projectId,taskId:task.taskId,attemptId:task.attemptId,idempotencyKey:`assignment-start-${claim!.fencingToken}`,requestDigest:canonicalAgentOperationDigest("startRun",task),fencingToken:claim!.fencingToken,task})).result!;
    const completionSnapshot=async(snapshotTask:AgentTask,snapshotJobId:string)=>(await admin.query(`SELECT to_jsonb(job) job,to_jsonb(run) run,
      (SELECT count(*)::int FROM builder.agent_runtime_results WHERE project_id=$1 AND run_id=$2) results,
      (SELECT count(*)::int FROM builder.inbox_events WHERE project_id=$1 AND consumer_identity='agent-job-completion') inbox,
      (SELECT count(*)::int FROM builder.agent_job_audit_events WHERE project_id=$1 AND job_id=$3 AND event_type='COMPLETED') audit,
      (SELECT count(*)::int FROM builder.outbox_events WHERE project_id=$1 AND aggregate_id=$3 AND event_type='AGENT_JOB_COMPLETED') outbox,
      COALESCE((SELECT jsonb_agg(to_jsonb(worker_row) ORDER BY worker_row.worker_process_instance_id) FROM (SELECT worker_process_instance_id,logical_worker_id,ownership_digest,policy_version,runtime_version,registered_at FROM builder.worker_process_instances WHERE worker_process_instance_id IN (job.worker_process_instance_id,run.worker_process_instance_id)) worker_row),'[]'::jsonb) worker_instances,
      COALESCE((SELECT jsonb_agg(to_jsonb(receipt_row) ORDER BY receipt_row.process_launch_id) FROM builder.process_launch_receipts receipt_row WHERE receipt_row.project_id=$1 AND receipt_row.job_id=$3),'[]'::jsonb) process_launch_receipts
      FROM builder.background_jobs job JOIN builder.agent_runtime_runs run ON run.project_id=job.project_id AND run.run_id=job.agent_run_id WHERE job.project_id=$1 AND job.id=$3`,[projectId,snapshotTask.runId,snapshotJobId])).rows[0]!;
    const context=createAgentJobCompletionContext(claim!);expect(context.assignment).not.toBeNull();const binding=context.assignment!;const foreignContexts=[
      {...context,assignment:{...binding,assignmentId:randomUUID()}},
      {...context,assignment:{...binding,agentId:randomUUID()}},
      {...context,assignment:{...binding,agentKey:"assignment-legal-other"}},
      {...context,assignment:{...binding,agentVersion:binding.agentVersion+1}},
      {...context,assignment:null},
    ];const completionGuard={jobId:claim!.jobId,workerId:claim!.workerId,workerProcessIdentity:claim!.workerProcessIdentity,processLaunchId:claim!.processLaunchId,claimId:claim!.claimId,fencingToken:claim!.fencingToken};const before=await completionSnapshot(task,enqueued.jobId);for(const foreign of foreignContexts){await expect(jobs.complete(foreign,result,completionGuard)).rejects.toThrow("COMPLETION_CONTEXT_MISMATCH");expect(await completionSnapshot(task,enqueued.jobId)).toEqual(before);}
    const completed=await jobs.complete(context,result);const audit=(await admin.query<{metadata:{assignmentId:string;agentId:string;agentKey:string;agentVersion:number} }>("SELECT metadata FROM builder.agent_job_audit_events WHERE project_id=$1 AND job_id=$2 AND event_type='COMPLETED'",[projectId,enqueued.jobId])).rows[0]!.metadata;expect(audit).toMatchObject({assignmentId:assigned.assignmentId,agentId:assigned.agentId,agentKey:assigned.agentKey,agentVersion:assigned.agentVersion});await assignments.releaseAssignment(assignmentCapability(),{assignmentId:assigned.assignmentId,projectId,jobId:enqueued.jobId,releasedBy:"completion-replay-release"});expect(await jobs.complete(context,result)).toEqual(completed);
    const releasedTask:AgentTask={...task,taskId:randomUUID(),attemptId:randomUUID(),runId:randomUUID(),inputRef:"synthetic/released-before-completion"};const releasedJob=await jobs.enqueue({task:releasedTask,messageId:randomUUID(),consumerIdentity:"assignment-release-before-completion",idempotencyKey:`assignment-release-${releasedTask.runId}`,requestDigest:canonicalAgentOperationDigest("enqueue",releasedTask),traceId:randomUUID(),maxRetries:0});const releasedAssigned=await assignments.assignActiveAgent(assignmentCapability(),input(releasedJob.jobId,{requiredRole:"LEGAL_DE_EU"}));const releasedClaim=await testWorkers.claimNext(jobs,"assignment-released-worker","assignment-released-claim",120_000);expect(releasedClaim?.jobId).toBe(releasedJob.jobId);const releasedResult=(await new FakeAgentRuntime({now:()=>new Date("2026-01-01T00:00:00Z")}).startRun({runId:releasedTask.runId,projectId,taskId:releasedTask.taskId,attemptId:releasedTask.attemptId,idempotencyKey:`assignment-released-start-${releasedClaim!.fencingToken}`,requestDigest:canonicalAgentOperationDigest("startRun",releasedTask),fencingToken:releasedClaim!.fencingToken,task:releasedTask})).result!;const releasedContext=createAgentJobCompletionContext(releasedClaim!);await assignments.releaseAssignment(assignmentCapability(),{assignmentId:releasedAssigned.assignmentId,projectId,jobId:releasedJob.jobId,releasedBy:"release-before-completion"});const releasedBefore=await completionSnapshot(releasedTask,releasedJob.jobId);await expect(jobs.complete(releasedContext,releasedResult)).rejects.toThrow("COMPLETION_ASSIGNMENT_NOT_ACTIVE");expect(await completionSnapshot(releasedTask,releasedJob.jobId)).toEqual(releasedBefore);
  });
});
