import { createHash,randomUUID } from "node:crypto";
import { Pool } from "pg";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { canonicalAgentOperationDigest,FakeAgentRuntime,type AgentResult } from "@software-builder/agent-runtime";
import type { PlanningJobResult,PlanningJobRole,PlanningResultOutcome,PlanningStatusView } from "@software-builder/workflow-engine";
import { AgentJobRepository,HmacCapabilityAuthority,PostgresDatabase,PostgresPlanningOrchestratorRepository,PostgresProjectContextIssuer,createAgentJobCompletionContext } from "./index.js";
import { migrate,resetDatabase } from "./migrations.js";

const adminUrl=process.env.TEST_DATABASE_URL;
const digest=(value:string)=>createHash("sha256").update(value).digest("hex");
const waitForDatabaseQuiescence=async(pool:Pool,timeoutMs=5_000)=>{const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){const active=await pool.query<{count:string}>("SELECT count(*) count FROM pg_stat_activity WHERE datname=current_database() AND pid<>pg_backend_pid()");if(Number(active.rows[0]!.count)===0)return;await new Promise(resolve=>setTimeout(resolve,5));}throw new Error("Timed out waiting for test database quiescence");};

describe("Planning Orchestrator PostgreSQL integration",()=>{
  let admin:Pool;let orchestrator:PostgresPlanningOrchestratorRepository;let runtimeJobs:AgentJobRepository;let database:PostgresDatabase;let authority:HmacCapabilityAuthority;let runtimeUrl:string;
  const versions=new Map<PlanningJobRole,number>();
  const registryIdentity=new Map<PlanningJobRole,{agentId:string;agentKey:string}>();

  beforeAll(async()=>{
    if(!adminUrl)throw new Error("TEST_DATABASE_URL ist fuer Planning-Orchestrator-Integration verpflichtend; Skips sind nicht zulaessig.");
    const parsed=new URL(adminUrl);if(!parsed.pathname.toLowerCase().endsWith("_test"))throw new Error("TEST_DATABASE_URL muss auf _test enden.");
    admin=new Pool({connectionString:adminUrl});await waitForDatabaseQuiescence(admin);await resetDatabase(admin,{connectionString:adminUrl,environment:"test"});expect(await migrate(admin)).toEqual([]);await admin.query("SELECT builder.provision_runtime_password('planning-runtime-integration-only-123')");await admin.query("SELECT builder.provision_context_password('planning-context-integration-only-123')");parsed.username="builder_app_login";parsed.password="planning-runtime-integration-only-123";runtimeUrl=parsed.toString();const contextUrl=new URL(parsed);contextUrl.username="builder_context_login";contextUrl.password="planning-context-integration-only-123";authority=new HmacCapabilityAuthority();database=await PostgresDatabase.connectRuntime(runtimeUrl,await PostgresProjectContextIssuer.connect(contextUrl.toString()),authority,authority);
    orchestrator=PostgresPlanningOrchestratorRepository.forTestHarness(admin);runtimeJobs=new AgentJobRepository(admin);
    for(const role of ["PLANNER","ARCHITECT","SECURITY","LEGAL_DE_EU"] as const)await activateRole(role);
  },30_000);

  afterAll(async()=>{await database?.close();if(admin){await admin.end();const cleanup=new Pool({connectionString:adminUrl!});try{await waitForDatabaseQuiescence(cleanup);await resetDatabase(cleanup,{connectionString:adminUrl!,environment:"test"});}finally{await cleanup.end();}}},30_000);

  async function activateRole(role:PlanningJobRole):Promise<void>{
    let identity=registryIdentity.get(role);if(!identity){identity={agentId:randomUUID(),agentKey:`planning-${role.toLowerCase().replaceAll("_","-")}`};registryIdentity.set(role,identity);await admin.query("INSERT INTO builder.agent_registry_identities(agent_key,agent_id,created_by) VALUES($1,$2,'planning-integration')",[identity.agentKey,identity.agentId]);}
    const version=(versions.get(role)??0)+1;versions.set(role,version);
    await admin.query(`INSERT INTO builder.agent_registry_versions(agent_id,agent_key,display_name,role,description,version,revision,status,instructions,allowed_capabilities,forbidden_capabilities,created_by)
      VALUES($1,$2,$3,$4,'Synthetic planning integration agent.',$5,$5,'ACTIVE','Process only synthetic Development Planning data.',ARRAY['planning.synthetic'],ARRAY['production.deploy','github.write'],'planning-integration')`,[identity.agentId,identity.agentKey,`Synthetic ${role}`,role,version]);
  }
  async function retireRole(role:PlanningJobRole):Promise<void>{const identity=registryIdentity.get(role)!;await admin.query("UPDATE builder.agent_registry_versions SET status='RETIRED' WHERE agent_key=$1 AND status='ACTIVE'",[identity.agentKey]);}
  async function newProject(label:string):Promise<{projectId:string;revision:string}>{const projectId=randomUUID();const revision=digest(`planning-revision:${label}`);await admin.query("INSERT INTO builder.projects(id,project_type,status) VALUES($1,'FULL_STACK_WEB','PLANNING')",[projectId]);return{projectId,revision};}

  async function completeRuntimeRole(status:PlanningStatusView,role:PlanningJobRole):Promise<PlanningJobResult>{
    const planningJob=(await orchestrator.listPlanningJobs(status.projectId,status.planningRunId)).find(job=>job.role===role);if(!planningJob)throw new Error(`Missing ${role} planning job`);
    const claim=await runtimeJobs.claimNext(`planning-worker-${role.toLowerCase()}`,`claim-${randomUUID()}`,120_000);if(!claim||claim.jobId!==planningJob.backgroundJobId)throw new Error(`Unexpected runtime claim for ${role}`);
    const command={runId:claim.task.runId,projectId:claim.projectId,taskId:claim.task.taskId,attemptId:claim.task.attemptId,idempotencyKey:`start-${claim.jobId}-${claim.fencingToken}`,requestDigest:canonicalAgentOperationDigest("startRun",claim.task),fencingToken:claim.fencingToken,task:claim.task};
    const runtime=(await new FakeAgentRuntime({now:()=>new Date("2026-07-15T12:00:00.000Z")}).startRun(command)).result;if(!runtime)throw new Error("Fake runtime did not produce a result");
    await runtimeJobs.complete(createAgentJobCompletionContext(claim),runtime);
    const resultId=(await admin.query<{agent_result_id:string}>("SELECT agent_result_id FROM builder.background_jobs WHERE id=$1",[claim.jobId])).rows[0]!.agent_result_id;
    return planningResult(planningJob.id,resultId,status.projectRevision,runtime);
  }
  function planningResult(jobId:string,runtimeResultId:string,revision:string,runtime:AgentResult,outcome:PlanningResultOutcome="PASS",requirements:PlanningJobResult["requirements"]=[]):PlanningJobResult{const artifact=runtime.artifacts[0]!;return{jobId,runtimeResultId,projectRevision:revision,outcome,objectRef:artifact.objectRef,digest:artifact.digest,requirements};}

  async function throughArchitect(label:string):Promise<{status:PlanningStatusView;security:PlanningJobResult;legal:PlanningJobResult}>{
    const input=await newProject(label);let status=await orchestrator.startPlanning(input.projectId,input.revision,"synthetic-owner");
    status=await orchestrator.handleJobResult(input.projectId,status.planningRunId,await completeRuntimeRole(status,"PLANNER"));
    status=await orchestrator.handleJobResult(input.projectId,status.planningRunId,await completeRuntimeRole(status,"ARCHITECT"));
    const security=await completeRuntimeRole(status,"SECURITY");const legal=await completeRuntimeRole(status,"LEGAL_DE_EU");return{status,security,legal};
  }
  async function successfulReview(label:string):Promise<PlanningStatusView>{const flow=await throughArchitect(label);const [security,legal]=await Promise.all([orchestrator.handleJobResult(flow.status.projectId,flow.status.planningRunId,flow.security),orchestrator.handleJobResult(flow.status.projectId,flow.status.planningRunId,flow.legal)]);expect([security.status,legal.status]).toContain("WAITING_FOR_OWNER_APPROVAL");return orchestrator.getPlanningStatus(flow.status.projectId,flow.status.planningRunId);}

  it("uses builder_app_login capability context and rejects cross-project or actor substitution",async()=>{
    const input=await newProject("capability-rls");const other=await newProject("capability-rls-other");const owner="capability-owner";
    const capability=authority.issueProject(input.projectId as never,{subject:owner,actorScope:"PLANNING_OWNER",allowedRoles:["PLANNING_OWNER"],allowedOperations:["planning:read","planning:append"]},120_000);const scoped=await database.createPlanningOrchestrator(capability);
    await expect(scoped.startPlanning(input.projectId,input.revision,"different-owner")).rejects.toThrow("PLANNING_CAPABILITY_ACTOR_MISMATCH");await expect(scoped.startPlanning(other.projectId,other.revision,owner)).rejects.toThrow("PLANNING_CAPABILITY_PROJECT_MISMATCH");
    let status=await scoped.startPlanning(input.projectId,input.revision,owner);expect(await scoped.listPlanningJobs(input.projectId,status.planningRunId)).toHaveLength(1);const naked=new Pool({connectionString:runtimeUrl});try{expect(Number((await naked.query<{count:string}>("SELECT count(*) count FROM builder.planning_runs")).rows[0]!.count)).toBe(0);}finally{await naked.end();}
    const otherCapability=authority.issueProject(other.projectId as never,{subject:"other-owner",actorScope:"PLANNING_OWNER",allowedRoles:["PLANNING_OWNER"],allowedOperations:["planning:read","planning:append"]},120_000);const otherScoped=await database.createPlanningOrchestrator(otherCapability);await expect(otherScoped.getPlanningStatus(input.projectId,status.planningRunId)).rejects.toThrow("PLANNING_CAPABILITY_PROJECT_MISMATCH");
    status=await scoped.handleJobResult(input.projectId,status.planningRunId,await completeRuntimeRole(status,"PLANNER"));status=await scoped.handleJobResult(input.projectId,status.planningRunId,await completeRuntimeRole(status,"ARCHITECT"));const security=await completeRuntimeRole(status,"SECURITY");const legal=await completeRuntimeRole(status,"LEGAL_DE_EU");await scoped.handleJobResult(input.projectId,status.planningRunId,security);status=await scoped.handleJobResult(input.projectId,status.planningRunId,legal);expect(status.status).toBe("WAITING_FOR_OWNER_APPROVAL");await expect(scoped.recordOwnerDecision(input.projectId,status.planningRunId,"APPROVE","different-owner","actor-substitution")).rejects.toThrow("PLANNING_CAPABILITY_ACTOR_MISMATCH");status=await scoped.recordOwnerDecision(input.projectId,status.planningRunId,"APPROVE",owner,"capability-approved");expect(status.status).toBe("READY_FOR_IMPLEMENTATION");expect(Number((await admin.query<{count:string}>("SELECT count(*) count FROM builder.project_context_grants WHERE project_id=$1 AND consumed_at IS NOT NULL",[input.projectId])).rows[0]!.count)).toBeGreaterThan(0);
  });

  it("linearisiert parallele Starts und doppelte Planner-/Architect-Ergebnisse ohne Jobduplikate",async()=>{
    const input=await newProject("parallel-start");const starts=await Promise.all([orchestrator.startPlanning(input.projectId,input.revision,"synthetic-owner"),orchestrator.startPlanning(input.projectId,input.revision,"synthetic-owner")]);expect(starts[0]).toEqual(starts[1]);let status=starts[0]!;
    const planner=await completeRuntimeRole(status,"PLANNER");const plannerResults=await Promise.all([orchestrator.handleJobResult(input.projectId,status.planningRunId,planner),orchestrator.handleJobResult(input.projectId,status.planningRunId,planner)]);status=plannerResults[0]!;expect((await orchestrator.listPlanningJobs(input.projectId,status.planningRunId)).filter(job=>job.role==="ARCHITECT")).toHaveLength(1);
    const architect=await completeRuntimeRole(status,"ARCHITECT");await Promise.all([orchestrator.handleJobResult(input.projectId,status.planningRunId,architect),orchestrator.handleJobResult(input.projectId,status.planningRunId,architect)]);const jobs=await orchestrator.listPlanningJobs(input.projectId,status.planningRunId);expect(jobs.filter(job=>job.role==="SECURITY")).toHaveLength(1);expect(jobs.filter(job=>job.role==="LEGAL_DE_EU")).toHaveLength(1);expect(jobs).toHaveLength(4);const securityBinding=jobs.find(job=>job.role==="SECURITY")!.assignment;await retireRole("SECURITY");await activateRole("SECURITY");expect((await orchestrator.listPlanningJobs(input.projectId,status.planningRunId)).find(job=>job.role==="SECURITY")!.assignment).toEqual(securityBinding);
    const security=await completeRuntimeRole(status,"SECURITY");const legal=await completeRuntimeRole(status,"LEGAL_DE_EU");await Promise.all([orchestrator.handleJobResult(input.projectId,status.planningRunId,security),orchestrator.handleJobResult(input.projectId,status.planningRunId,legal)]);
  });

  it("requires both parallel reviews, survives restart/resume, and creates no executor",async()=>{
    const flow=await throughArchitect("review-barrier");let status=await orchestrator.handleJobResult(flow.status.projectId,flow.status.planningRunId,flow.security);expect(status.status).toBe("SECURITY_LEGAL_REVIEW");await expect(orchestrator.recordOwnerDecision(status.projectId,status.planningRunId,"APPROVE","synthetic-owner","too-early")).rejects.toThrow("PLANNING_OWNER_DECISION_NOT_ALLOWED");
    const restarted=PostgresPlanningOrchestratorRepository.forTestHarness(admin);status=await restarted.resumePlanning(status.projectId,status.planningRunId);expect(status.status).toBe("SECURITY_LEGAL_REVIEW");expect(await restarted.listPlanningJobs(status.projectId,status.planningRunId)).toHaveLength(4);
    status=await restarted.handleJobResult(status.projectId,status.planningRunId,flow.legal);expect(status.status).toBe("WAITING_FOR_OWNER_APPROVAL");expect((await admin.query("SELECT 1 FROM builder.planning_jobs WHERE planning_run_id=$1 AND role NOT IN ('PLANNER','ARCHITECT','SECURITY','LEGAL_DE_EU')",[status.planningRunId])).rowCount).toBe(0);await expect(admin.query("INSERT INTO builder.planning_owner_decisions(project_id,planning_run_id,decision,decided_by,reason_ref,approved_project_revision) VALUES($1,$2,'APPROVE','synthetic-owner','partial-owner-decision',$3)",[status.projectId,status.planningRunId,status.projectRevision])).rejects.toThrow("owner decision and planning run terminal state must commit atomically");expect((await admin.query("SELECT 1 FROM builder.planning_owner_decisions WHERE planning_run_id=$1",[status.planningRunId])).rowCount).toBe(0);
  });

  it("persists immutable owner APPROVE and the exact approved revision",async()=>{let status=await successfulReview("owner-approve");status=await orchestrator.recordOwnerDecision(status.projectId,status.planningRunId,"APPROVE","synthetic-owner","development-plan-approved");expect(status).toMatchObject({status:"READY_FOR_IMPLEMENTATION",ownerDecision:{decision:"APPROVE",decidedBy:"synthetic-owner",reason:"development-plan-approved",approvedProjectRevision:status.projectRevision}});expect(await orchestrator.recordOwnerDecision(status.projectId,status.planningRunId,"APPROVE","synthetic-owner","development-plan-approved")).toEqual(status);await expect(orchestrator.recordOwnerDecision(status.projectId,status.planningRunId,"REJECT","synthetic-owner","conflict")).rejects.toThrow("PLANNING_OWNER_DECISION_CONFLICT");expect((await orchestrator.resumePlanning(status.projectId,status.planningRunId)).status).toBe("READY_FOR_IMPLEMENTATION");await expect(admin.query("UPDATE builder.planning_owner_decisions SET reason_ref='mutated' WHERE planning_run_id=$1",[status.planningRunId])).rejects.toThrow();await expect(admin.query("UPDATE builder.planning_runs SET status='PLANNING' WHERE id=$1",[status.planningRunId])).rejects.toThrow("terminal planning run is immutable");});

  it("persists immutable owner REJECT without further jobs",async()=>{let status=await successfulReview("owner-reject");const before=(await orchestrator.listPlanningJobs(status.projectId,status.planningRunId)).length;status=await orchestrator.recordOwnerDecision(status.projectId,status.planningRunId,"REJECT","synthetic-owner","development-plan-rejected");expect(status).toMatchObject({status:"REJECTED",ownerDecision:{decision:"REJECT"}});expect(await orchestrator.listPlanningJobs(status.projectId,status.planningRunId)).toHaveLength(before);});

  it.each(["SECURITY","LEGAL_DE_EU"] as const)("makes %s BLOCK terminal and unable to race owner approval",async role=>{const flow=await throughArchitect(`block-${role}`);const block=role==="SECURITY"?{...flow.security,outcome:"BLOCK" as const}:{...flow.legal,outcome:"BLOCK" as const};const pass=role==="SECURITY"?flow.legal:flow.security;await orchestrator.handleJobResult(flow.status.projectId,flow.status.planningRunId,pass);const raced=await Promise.allSettled([orchestrator.handleJobResult(flow.status.projectId,flow.status.planningRunId,block),orchestrator.recordOwnerDecision(flow.status.projectId,flow.status.planningRunId,"APPROVE","synthetic-owner","cannot-win")]);expect(raced[0]).toMatchObject({status:"fulfilled",value:{status:"BLOCKED",blockCode:"REVIEW_BLOCK",blockRole:role}});expect(raced[1]).toMatchObject({status:"rejected"});const status=await orchestrator.getPlanningStatus(flow.status.projectId,flow.status.planningRunId);expect(status.status).toBe("BLOCKED");expect((await orchestrator.resumePlanning(status.projectId,status.planningRunId)).status).toBe("BLOCKED");});

  it("closes the minimized PASS_WITH_REQUIREMENTS set in the result transaction",async()=>{const flow=await throughArchitect("requirements");const required={...flow.legal,outcome:"PASS_WITH_REQUIREMENTS" as const,requirements:[{code:"NOTICE_REQUIRED",ref:"synthetic/legal/notice"},{code:"RETENTION_LIMIT",ref:"synthetic/privacy/retention"}]};const pendingLegal=(await orchestrator.listPlanningJobs(flow.status.projectId,flow.status.planningRunId)).find(job=>job.role==="LEGAL_DE_EU")!;await expect(admin.query("INSERT INTO builder.planning_review_requirements(project_id,planning_run_id,planning_job_id,requirement_code,requirement_ref) VALUES($1,$2,$3,'UNBOUND_STAGE','synthetic/legal/unbound')",[flow.status.projectId,flow.status.planningRunId,pendingLegal.id])).rejects.toThrow("staged planning requirements and PASS_WITH_REQUIREMENTS must commit atomically");let status=await orchestrator.handleJobResult(flow.status.projectId,flow.status.planningRunId,required);expect(status.status).toBe("SECURITY_LEGAL_REVIEW");const legal=(await orchestrator.listPlanningJobs(status.projectId,status.planningRunId)).find(job=>job.role==="LEGAL_DE_EU")!;expect(legal.requirements).toEqual(required.requirements);await expect(admin.query("INSERT INTO builder.planning_review_requirements(project_id,planning_run_id,planning_job_id,requirement_code,requirement_ref) VALUES($1,$2,$3,'LATE_APPEND','synthetic/legal/late')",[status.projectId,status.planningRunId,legal.id])).rejects.toThrow("planning requirements can only be staged before");status=await orchestrator.handleJobResult(flow.status.projectId,flow.status.planningRunId,flow.security);expect(status.status).toBe("WAITING_FOR_OWNER_APPROVAL");expect((await admin.query("SELECT requirement_code,requirement_ref FROM builder.planning_review_requirements WHERE planning_job_id=$1 ORDER BY requirement_code",[legal.id])).rows).toEqual([{requirement_code:"NOTICE_REQUIRED",requirement_ref:"synthetic/legal/notice"},{requirement_code:"RETENTION_LIMIT",requirement_ref:"synthetic/privacy/retention"}]);status=await orchestrator.recordOwnerDecision(status.projectId,status.planningRunId,"APPROVE","synthetic-owner","requirements-approved");expect(status.status).toBe("READY_FOR_IMPLEMENTATION");await expect(admin.query("INSERT INTO builder.planning_review_requirements(project_id,planning_run_id,planning_job_id,requirement_code,requirement_ref) VALUES($1,$2,$3,'POST_APPROVAL_APPEND','synthetic/legal/post-approval')",[status.projectId,status.planningRunId,legal.id])).rejects.toThrow("planning requirements can only be staged before");await expect(admin.query("DELETE FROM builder.planning_review_requirements WHERE planning_job_id=$1",[legal.id])).rejects.toThrow();});

  it("serializes job snapshots so result and requirement commits are never mixed",async()=>{const flow=await throughArchitect("snapshot-serialization");const requirement={code:"SNAPSHOT_REQUIREMENT",ref:"synthetic/legal/snapshot"};const legalResult={...flow.legal,outcome:"PASS_WITH_REQUIREMENTS" as const,requirements:[requirement]};const client=await admin.connect();try{await client.query("BEGIN");await client.query("SELECT 1 FROM builder.planning_runs WHERE project_id=$1 AND id=$2 FOR UPDATE",[flow.status.projectId,flow.status.planningRunId]);await client.query("INSERT INTO builder.planning_review_requirements(project_id,planning_run_id,planning_job_id,requirement_code,requirement_ref) VALUES($1,$2,$3,$4,$5)",[flow.status.projectId,flow.status.planningRunId,legalResult.jobId,requirement.code,requirement.ref]);await client.query("UPDATE builder.planning_jobs SET runtime_result_id=$4,outcome=$5,result_object_ref=$6,result_digest=$7,completed_at=clock_timestamp() WHERE project_id=$1 AND planning_run_id=$2 AND id=$3",[flow.status.projectId,flow.status.planningRunId,legalResult.jobId,legalResult.runtimeResultId,legalResult.outcome,legalResult.objectRef,legalResult.digest]);let settled=false;const snapshotPromise=orchestrator.listPlanningJobs(flow.status.projectId,flow.status.planningRunId).then(value=>{settled=true;return value;});await new Promise(resolve=>setTimeout(resolve,25));expect(settled).toBe(false);await client.query("COMMIT");const snapshot=await snapshotPromise;expect(snapshot.find(job=>job.role==="LEGAL_DE_EU")).toMatchObject({outcome:"PASS_WITH_REQUIREMENTS",requirements:[requirement]});}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}await orchestrator.handleJobResult(flow.status.projectId,flow.status.planningRunId,legalResult);const status=await orchestrator.handleJobResult(flow.status.projectId,flow.status.planningRunId,flow.security);expect(status.status).toBe("WAITING_FOR_OWNER_APPROVAL");});

  it("rejects a wrong revision, stale/conflicting replay, and owner approval before reviews",async()=>{const input=await newProject("revision-guard");let status=await orchestrator.startPlanning(input.projectId,input.revision,"synthetic-owner");const planner=await completeRuntimeRole(status,"PLANNER");await expect(orchestrator.handleJobResult(input.projectId,status.planningRunId,{...planner,projectRevision:"f".repeat(64)})).rejects.toThrow("PLANNING_PROJECT_REVISION_MISMATCH");status=await orchestrator.handleJobResult(input.projectId,status.planningRunId,planner);await expect(orchestrator.handleJobResult(input.projectId,status.planningRunId,{...planner,digest:"e".repeat(64)})).rejects.toThrow("PLANNING_RESULT_CONFLICT");await expect(orchestrator.recordOwnerDecision(input.projectId,status.planningRunId,"APPROVE","synthetic-owner","too-early")).rejects.toThrow("PLANNING_OWNER_DECISION_NOT_ALLOWED");status=await orchestrator.handleJobResult(input.projectId,status.planningRunId,await completeRuntimeRole(status,"ARCHITECT"));const security=await completeRuntimeRole(status,"SECURITY");const legal=await completeRuntimeRole(status,"LEGAL_DE_EU");await Promise.all([orchestrator.handleJobResult(input.projectId,status.planningRunId,security),orchestrator.handleJobResult(input.projectId,status.planningRunId,legal)]);});

  it("blocks fail-closed without a partial job when Planner is unavailable",async()=>{await retireRole("PLANNER");try{const input=await newProject("missing-planner");const status=await orchestrator.startPlanning(input.projectId,input.revision,"synthetic-owner");expect(status).toMatchObject({status:"BLOCKED",blockCode:"NO_ACTIVE_AGENT_VERSION",blockRole:"PLANNER"});expect(await orchestrator.listPlanningJobs(input.projectId,status.planningRunId)).toHaveLength(0);expect((await admin.query("SELECT 1 FROM builder.agent_runtime_tasks WHERE project_id=$1",[input.projectId])).rowCount).toBe(0);}finally{await activateRole("PLANNER");}});

  it("persists Planner result but no Architect job when Architect is unavailable",async()=>{const input=await newProject("missing-architect");let status=await orchestrator.startPlanning(input.projectId,input.revision,"synthetic-owner");const planner=await completeRuntimeRole(status,"PLANNER");await retireRole("ARCHITECT");try{status=await orchestrator.handleJobResult(input.projectId,status.planningRunId,planner);expect(status).toMatchObject({status:"BLOCKED",blockRole:"ARCHITECT"});const jobs=await orchestrator.listPlanningJobs(input.projectId,status.planningRunId);expect(jobs).toHaveLength(1);expect(jobs[0]).toMatchObject({role:"PLANNER",outcome:"PASS"});}finally{await activateRole("ARCHITECT");}});

  it.each(["SECURITY","LEGAL_DE_EU"] as const)("creates neither review job when %s has no active agent",async missingRole=>{const input=await newProject(`missing-${missingRole}`);let status=await orchestrator.startPlanning(input.projectId,input.revision,"synthetic-owner");status=await orchestrator.handleJobResult(input.projectId,status.planningRunId,await completeRuntimeRole(status,"PLANNER"));const architect=await completeRuntimeRole(status,"ARCHITECT");await retireRole(missingRole);try{status=await orchestrator.handleJobResult(input.projectId,status.planningRunId,architect);expect(status).toMatchObject({status:"BLOCKED",blockRole:missingRole});const jobs=await orchestrator.listPlanningJobs(input.projectId,status.planningRunId);expect(jobs.map(job=>job.role)).toEqual(["PLANNER","ARCHITECT"]);expect((await admin.query("SELECT 1 FROM builder.agent_runtime_tasks WHERE project_id=$1 AND role IN ('SECURITY','LEGAL')",[input.projectId])).rowCount).toBe(0);}finally{await activateRole(missingRole);}});

  it("rejects direct run shortcuts, prefilled results, and inconsistent runtime-assignment bindings",async()=>{const status=await successfulReview("database-insert-guards");const invalidRun=randomUUID();await expect(admin.query("INSERT INTO builder.planning_runs(id,project_id,project_revision,status,requested_by,blocked_at,block_code,block_role) VALUES($1,$2,$3,'BLOCKED','synthetic-owner',clock_timestamp(),'REVIEW_BLOCK','SECURITY')",[invalidRun,status.projectId,digest("invalid-initial-run")])).rejects.toThrow("planning runs must start in PLANNING");const runId=randomUUID();const revision=digest("direct-job-guard-run");await admin.query("INSERT INTO builder.planning_runs(id,project_id,project_revision,status,requested_by) VALUES($1,$2,$3,'PLANNING','synthetic-owner')",[runId,status.projectId,revision]);const jobs=await orchestrator.listPlanningJobs(status.projectId,status.planningRunId);const planner=jobs.find(job=>job.role==="PLANNER")!;const architect=jobs.find(job=>job.role==="ARCHITECT")!;const insert=`INSERT INTO builder.planning_jobs(id,project_id,planning_run_id,project_revision,role,background_job_id,runtime_run_id,assignment_id,input_ref,runtime_result_id,outcome,result_object_ref,result_digest,completed_at) VALUES($1,$2,$3,$4,'PLANNER',$5,$6,$7,'synthetic/direct-job',$8,$9,$10,$11,$12)`;await expect(admin.query(insert,[randomUUID(),status.projectId,runId,revision,planner.backgroundJobId,planner.runtimeRunId,planner.assignment.assignmentId,planner.runtimeResultId,"PASS",planner.resultObjectRef,planner.resultDigest,new Date()])).rejects.toThrow("planning jobs must start without a result");const emptyResult=[null,null,null,null,null] as const;await expect(admin.query(insert,[randomUUID(),status.projectId,runId,revision,planner.backgroundJobId,planner.runtimeRunId,architect.assignment.assignmentId,...emptyResult])).rejects.toThrow("planning job runtime and assignment binding is inconsistent");await expect(admin.query(insert,[randomUUID(),status.projectId,runId,revision,architect.backgroundJobId,architect.runtimeRunId,architect.assignment.assignmentId,...emptyResult])).rejects.toThrow("planning job runtime and assignment binding is inconsistent");await expect(admin.query(insert,[randomUUID(),status.projectId,runId,revision,planner.backgroundJobId,architect.runtimeRunId,planner.assignment.assignmentId,...emptyResult])).rejects.toThrow("planning job runtime and assignment binding is inconsistent");await admin.query("UPDATE builder.agent_assignments SET assignment_status='RELEASED',released_at=clock_timestamp(),released_by='synthetic-guard-test' WHERE assignment_id=$1",[planner.assignment.assignmentId]);await expect(admin.query(insert,[randomUUID(),status.projectId,runId,revision,planner.backgroundJobId,planner.runtimeRunId,planner.assignment.assignmentId,...emptyResult])).rejects.toThrow("planning job runtime and assignment binding is inconsistent");});

  it("rolls back an unknown database failure without run, runtime job, assignment, or outbox partial state",async()=>{const input=await newProject("rollback");await admin.query("CREATE FUNCTION builder.test_fail_planning_job_insert() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'SYNTHETIC_PLANNING_POST_MUTATION_FAILURE'; END $$");try{await admin.query("CREATE TRIGGER test_fail_planning_job_insert AFTER INSERT ON builder.planning_jobs FOR EACH ROW WHEN (NEW.project_id=$$"+input.projectId+"$$::uuid) EXECUTE FUNCTION builder.test_fail_planning_job_insert()");await expect(orchestrator.startPlanning(input.projectId,input.revision,"synthetic-owner")).rejects.toThrow("SYNTHETIC_PLANNING_POST_MUTATION_FAILURE");expect((await admin.query("SELECT 1 FROM builder.planning_runs WHERE project_id=$1",[input.projectId])).rowCount).toBe(0);expect((await admin.query("SELECT 1 FROM builder.agent_runtime_tasks WHERE project_id=$1",[input.projectId])).rowCount).toBe(0);expect((await admin.query("SELECT 1 FROM builder.background_jobs WHERE project_id=$1",[input.projectId])).rowCount).toBe(0);expect((await admin.query("SELECT 1 FROM builder.agent_assignments WHERE project_id=$1",[input.projectId])).rowCount).toBe(0);expect((await admin.query("SELECT 1 FROM builder.outbox_events WHERE project_id=$1",[input.projectId])).rowCount).toBe(0);}finally{await admin.query("DROP TRIGGER IF EXISTS test_fail_planning_job_insert ON builder.planning_jobs");await admin.query("DROP FUNCTION IF EXISTS builder.test_fail_planning_job_insert()");}});
});
